### ISSUE TITLE
1.6 supports 4 wifi chips ony

### ISSUE THREAD

**Issue by gba-gbob** [bortek/EZ-WifiBroadcast#103]
As per below code if card does not fall under names  stated   it does not get put into monitor mode  and fails to transmit receive packets. Would expect either error or sensible defaults for other devices.

https://github.com/bortek/EZ-WifiBroadcast/blob/master/wifibroadcast-scripts/profile#L230
https://github.com/bortek/EZ-WifiBroadcast/blob/master/wifibroadcast-scripts/profile#L307

**Comment by gba-gbob** [comment]
Hi Rodizio1, I have MediaTek MT7601 which does not get initiated but is in the wiki. I also can confirm that it works. Thanks for quick response

**Comment by gba-gbob** [comment]
In addition it would be great to have ability to provide card config  files based on driver name / usb id ? in this case new card can be added by users on the fly just by creating new file, and source it from the main script.

**Comment by rodizio1** [comment]
1.6RC6 has just been released, would be nice if you could report back if the mt7601 is working now.

**Comment by gba-gbob** [comment]
Can confirm works fine, I cannot see changes being published in master

**Comment by rodizio1** [comment]
Thanks for confirming. Sourcecode on Github will follow (sorry, I'm always behind with that). Sourcecode in the image is there.
