### ISSUE TITLE
OSD build fails for LTM

### ISSUE THREAD

**Issue by seeul8er** [bortek/EZ-WifiBroadcast#106]
replacing `#define MAVLINK` with `#define LTM` in osdconfig.txt causes a compiler error. Can anyone confirm?

WBC 1.6 RC5

**Comment by rodizio1** [comment]
Yes, I can confirm. Bug, forgot to rename/change some variables. Will be fixed in the next release.

**Comment by rodizio1** [comment]
Fixed in 1.6RC6
