### ISSUE TITLE
Experiences with NanoPi Neo2 or Neo Core2

### ISSUE THREAD

**Issue by wstoettinger** [bortek/EZ-WifiBroadcast#107]
Hello!

I'd like to create a very lightweight and compact solution in order to minimize the reduction in flight time when put on the Mavic Pro. 

Has anyone got experience with NanoPi Neo2 or Neo Core2?

Thanks in advance!

**Comment by rodizio1** [comment]
Since nobody answered and I think it doesn't really make much sense putting a lot of effort in different hardware, I'll close this.
