### ISSUE TITLE
Build does not work for wifibroadcast

### ISSUE THREAD

**Issue by Hyphen90** [bortek/EZ-WifiBroadcast#11]
Hi, there are duplicated symbols in the build - for example:

rx_lib.o:(.data+0x0): multiple definition of `max_block_num'
rx.o:(.data+0x10): first defined here

Please can you clarify/fix it?
And are all the changes for the 1.5 version included in this repository?
You wrote in another issue/topic that also every code change is included in the image file, but I did not find the patched kernel source - or is the kernel the only part which you build on your host? And in /root/wifibroadcast are other sources than in this repository - are these the latest and is the repo obsolete so far?

Thanks ahead

**Comment by rodizio1** [comment]
Sorry, the code in the Github Repo is outdated, I have only maintained the wiki lately. The source in the image is the latest version. I'll see that I upload v1.5 code and also the kernel patches on the weekend ...

**Comment by titeuf007** [comment]
thanks rodizio for this great project
i hope you will continous to improve it! you are the one project i like most with arducopter and betaflight!
the only one thing missing in this great project is Automatic frequency hopping to be complet
have a nice day

**Comment by bortek** [comment]
I keep this open until you have time to add the code.

**Comment by terial** [comment]
hey @rodizio1 any updates on getting the code updated? thanks!

**Comment by rodizio1** [comment]
I have updated the sources on Github to the 1.5 sources now.
