### ISSUE TITLE
rx_rc_telemetry.c 1.6 RC 6 int i with out init

### ISSUE THREAD

**Issue by user1321** [bortek/EZ-WifiBroadcast#111]
Good Day!
First of all - thank you for a great project!
I am trying to run it under Kali Linux right now and getting "Segmentation Fault" error after:
/rx_rc_telemerty -p 3 -o 0 -b 57600 -s /dev/ttyUSB0 -r 1 wlan0
executed.
I am noticed that variable created at line 600:
"int i;"
 not initialized till line 819:
"for(i=0; i<num_interfaces; ++i) {
 , but used at line 816:
packetcounter_ts_now[i] = current_timestamp();
After changed line 600 to: int i =0 app not crash anymore (I am still not sure how it mast work in normal way :-\)
Looks like that raspberry pi OS works with memory in different way  (RP OS assign it no 0 at createing point, or just don`t care at random memory record? ) if it not cause application crash instantly.
In any case, would be nice to set it to 0 in future releases. Once again, thank you for a great project.
source: [rx_rc_telemetry.c.txt](https://github.com/bortek/EZ-WifiBroadcast/files/1887897/rx_rc_telemetry.c.txt)

**Comment by rodizio1** [comment]
Strange that it works at all, indeed :) Thanks for pointing it out, will be fixed in the next release.

Please note, the rx_rc_telemetry (without _buf) suffers from packetloss due to re-ordering when using more than one RX wifi card, you want to use rx_rc_telemetry_buf if you use multiple cards.
