### ISSUE TITLE
OSD Add proximity sensor and rangefinder mesurements

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#112]
Hello,

It will be cool feature to display measurement from proximity sensors and rangefinders when using ARDUCOPTER or ARDUPILOT.

**Comment by roque-canales** [comment]
Hello Rodizio, 

here you have description of mavlink proximity messages:
http://mavlink.org/messages/common#DISTANCE_SENSOR

**Comment by geofrancis** [comment]
this would be good as long as it can also show rangefinder altitude.

**Comment by rodizio1** [comment]
Regarding obstacle avoidance: Just displaying 8 numbers probably doesn't make too much sense, it'd need some kind of graphical display and additional logic to make something turn red or warn when things come too near, that would be too much work and I don't even know how to do that.

Displaying the rangefinder distance should be no problem I guess.

**Comment by roque-canales** [comment]
ok, so Don't upgrade OSD, but please upgrade EZWBC for it relay DISTANCE SENSOR MSG and RANGEFINDER masg to mission planner.
