### ISSUE TITLE
Wiki - Home - Screen/Monitors: Add ZEISS Cinemizer OLED

### ISSUE THREAD

**Issue by careyer** [bortek/EZ-WifiBroadcast#113]
You might want to add the ZEISS Cinemizer OLED as well in the Wiki as a supported device.
It works like a charm and picture quality is superb!

Cheers!

**Comment by bortek** [comment]
Glad this works and all hdmi capable screens will do as well. We though don't have a section for screens/monitors and it will be very tedious to keep it up to date. Hope you can understand.
