### ISSUE TITLE
mavlink-router on TX pi

### ISSUE THREAD

**Issue by terial** [bortek/EZ-WifiBroadcast#114]
Hey @rodizio1 , awesome work! I have been trying for quiet some time to get mavlink-router to run on the TX pi. Issue is on my pixhawk 2 one serial port is for my dragonlink v3 reciever and the other telemetry 2 is connected to the rpi3 GPIO for uart. I cant seem to get the incoming serial from telemetry 2 to the rpi3 split/echo'd using tools like socat, netcat etc. Is there a way I can get it to run so that mavlink-router is running and the TX pi is sending out OSD data from the same serial stream? I have been using a setup right now with just mavlink-router and samba so the log files are fast and easy to get. I would love to get ez wifibroadcast integrated as well.

**Comment by rodizio1** [comment]
You just want to transmit the telemetry data down to the ground and display it there? f I understand correctly, what you are trying to do, that should work right out of the box.

Another alternative would be to use your Dragonlink to transmit the telemetry down to the ground and connect the serialport of the Dragonlink RX to the serialport of the RX Pi (this can simply be configured in wifibroadcast-1.txt
