### ISSUE TITLE
No network connection on ETHERNET_HOTSPOT=Y

### ISSUE THREAD

**Issue by zenuavsolutions** [bortek/EZ-WifiBroadcast#117]
If I set the ETHERNET_HOTSPOT = Y option, I can not get a network connection. Also, the message "Ethernet connected 192.bla.blub" does not appear in the OSD. If I set ETHERNET_HOTSPOT = N, the Pi will connect to the network, but of course the services for video stream and mavlink are not running(?) Am I wrong or is this a bug?

But nevertheless, this is great software !! Thank you for sharing it!

**Comment by rodizio1** [comment]
This is intended behaviour, in that case, the Pi acts as a Hotspot (i.e. runs a DHCP server that gives out an IP to a connected PC/Notebook).When you connect a Notebook to it, you'll get the telemetry and video forwarded to the notebook.

With setting 'N' the Pi acts as a Client and will get an IP from your Router's DHCP server (and display that), it's just meant for being able to login to the linux console.

**Comment by andrew-grischenko** [comment]
I'm streaming video without hotspot from raspberry by giving the following commands:

```
sudo su
ionice -c 1 -n 4 nice -n -5 cat /root/videofifo2 | nice -n -5 gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay ! "application/x-rtp,payload=(int)103,clock-rate=(int)90000" ! udpsink host=[YOUR DESTINATION IP] port=[YOUR DESTINATION PORT]
```

Then on the receiving side you can do different things, I use Janus server gateway to translate it to web browser clients.

**Comment by zenuavsolutions** [comment]
Ah i got it, thank you very much! Teen you can close the issue...
