### ISSUE TITLE
1.6 RC6 mission planner cant get params

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#121]
Hello just upgading from 1.6RC5 to 1.6RC6 when I connect on udp 14550 port through mission planner I get telemetry downlink but uplink no work. And mission planner can't request params….

There is anybody that experienced this issue ? there's is parameter to set on pixhawk side like SYS ID or other?

**Comment by rodizio1** [comment]
Can you try setting RC=mavlink?

One user on RCGroups reported that the uplink didn't work until he enabled RC (which doesn't really make sense, could be a bug).

**Comment by roque-canales** [comment]
Yes setting param RC to mavlink on both side work.

**Comment by rodizio1** [comment]
Thanks for confirming the bug :)
