### ISSUE TITLE
EZWBC 1.6 dont relay rangefinder and distance sensor message to mission planner

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#123]

**Comment by rodizio1** [comment]
Probably also caused by incompatibility of the mavlink.org Mavlink libs I use and different ArduCopter libs. Will be fixed as soon as I've written a Mavlink parser that doesn't suffer from these incompatibilities.

**Comment by roque-canales** [comment]
Hello Rodizio, What's up ?

**Comment by bortek** [comment]
I am trying to clean up the clutter @Yes21 , do you know if this is still relevant or can we close it ?

**Comment by Yes21** [comment]
Mavlink2 implementation will solve it.
