### ISSUE TITLE
Question on Telemetry

### ISSUE THREAD

**Issue by JamesCordell** [bortek/EZ-WifiBroadcast#128]
How does the telemetry information get from the flight controller to the r pi? I cannot find and details of wiring. Does it us the serial tx on the FC to rx on the R PI. If so what format is supported? Do I need to invert the signal if using frsky telemetry with a transistor?

**Comment by rodizio1** [comment]
https://github.com/bortek/EZ-WifiBroadcast/wiki/How-to's#setting-up-telemetry-and-osd

The Pi serialport is not inverted, if your FC puts out an inverted signal, you'll need to make it not inverted before.

Also make sure your FC gives out 3.3V logic level.

**Comment by JamesCordell** [comment]
Thanks.
