### ISSUE TITLE
1.6RC6 : impossible to connect to the RX via SSH

### ISSUE THREAD

**Issue by Yes21** [bortek/EZ-WifiBroadcast#136]
I have enabled ETHERNET_HOTSPOT and WIFI_HOTSPOT, and they are up.
But I cannot ssh to both !
(Firewall is disabled)

`root@yves-CX61-2PC:~# ifconfig
enp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::42eb:4fc0:18dc:7420  prefixlen 64  scopeid 0x20<link>
        ether 44:8a:5b:ec:e6:1e  txqueuelen 1000  (Ethernet)
        RX packets 5422  bytes 698096 (698.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2599  bytes 355310 (355.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 19  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Boucle locale)
        RX packets 22066  bytes 1725117 (1.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22066  bytes 1725117 (1.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.2  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::f1f6:a706:5d27:f160  prefixlen 64  scopeid 0x20<link>
        ether 6c:71:d9:f6:b1:e1  txqueuelen 1000  (Ethernet)
        RX packets 383046  bytes 387414985 (387.4 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 301024  bytes 39414909 (39.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@yves-CX61-2PC:~# ssh 192.168.1.2
ssh: connect to host 192.168.1.2 port 22: Connection refused
root@yves-CX61-2PC:~# ssh 192.168.2.2
ssh: connect to host 192.168.2.2 port 22: Connection refused
`

**Comment by JamesCordell** [comment]
can you do a netstat and see if port 22 is listening?

**Comment by Yes21** [comment]
I don't understand why, but it works with 192.168.1.1 (ETHER) and 
192.168.2.1 (WIFI) !

**Comment by rodizio1** [comment]
192.168.1.2 (ethernet) and 192.168.2.2 (wifi) is the IP address handed out to your PC, the Pi has 192.168.1.1 and 192.168.2.1.

You tried connecting to your own PC with 1.2 and 2.2, thats why it didn't work ;)

**Comment by Yes21** [comment]
Thanks.
I'm now logged on the RX Pi, but can't install anything because no internet connection ...
All that I've tried to share the internet connection from my host doesn't work.
And I can't also connect the Pi to wifi.
I was able to do it on a "normal" raspbian, but I'm totally confused with your modified version !!

How do you do to get an internet connection on your RX Pi ?

Sorry to be like a newbie ...

**Comment by rodizio1** [comment]
If you want Internet on the Pi, use it as a client. To do that,disable Ethernet Hotspot and connect it to your router via Ethernet before powering up the Pi. It will show the IP it got from your router after starting up (or look into your router's webinterface, it'll show up as wifibroadcast-rx or wifibroadcast-tx there).

Be careful with installing software and making changes, you need to know what you're doing, if you run apt-get upgrade for example you'll most likely screw everything up.

Make small changes at a time and also make sure you understand exactly what they do and what things they change.
