### ISSUE TITLE
Debugging help

### ISSUE THREAD

**Issue by JamesCordell** [bortek/EZ-WifiBroadcast#137]
Hi

First off, nice osd by the way, this project is amazing, good work.

How would I run this osd on a single pi, that has the telemetry feed from the flight controller, overlaid with the camera image output to the hdmi or cvbs signal for simple debugging and testing. i.e no wifi stuff.

**Comment by rodizio1** [comment]
The OSD accepts data on stdin, something like "cat /dev/serial0 | osd"  should work. And run raspivid in preview mode.
