### ISSUE TITLE
RC passyhrough

### ISSUE THREAD

**Issue by bazyl78** [bortek/EZ-WifiBroadcast#138]
Can you try to do rc passthrough? For example ppm input on ground pi and ppm output on air unit?. That would be great to use this as a module for rc transmitter and have all in one rc control solution like OpenSolo.

**Comment by rodizio1** [comment]
Sorry it's not possible to output PPM in a 100% reliable way on the air Pi. 

You can use a PPM to USB-Joystick adapter or a Transmitter with integrated USB-Joystick support like a Taranis on the ground Pi though.

On the air Pi, you can chose between several different protocols like Mavlink, IBUS, SUMD,  XBUS (all digital and checksummed, thus 100% safe and reliable), most flight controls support at least on of these.

**Comment by careyer** [comment]
Sorry PWM / PPM / CPPM ... is not possible on RaspberryPi, see: https://github.com/bortek/EZ-WifiBroadcast/wiki/RC-:-regular-RC-protocols
