### ISSUE TITLE
Question about RX

### ISSUE THREAD

**Issue by radlxau** [bortek/EZ-WifiBroadcast#139]
Hi Im just trying to figure it all out but does anyone know in theory how many RX units you would be able to connect to a single TX? or is it just a point to single point system?

**Comment by rodizio1** [comment]
You can connect up to three Atheros cards or up to five Ralink cards to a single RX Raspberry (for diversity) and use as many RX Raspberrys as you want.

The TX just broadcasts the data and isn't even aware that there is a RX listening, there is no 'connection' or 'link' or 'association' between TX and RX, it behaves similar to analog video systems in that regard.
