### ISSUE TITLE
Show Warnings PX4

### ISSUE THREAD

**Issue by tops4u** [bortek/EZ-WifiBroadcast#147]
Is it possible to show Warnings and other Text Messages in the OSD? I made the experience that AC and PX4 do handle this differently. I noticed that Compass works only sporadically while most other Items work ok with PX4. 

Is it possible to show accumulated Current consumption, instead of Battery Percentage?

**Comment by dposea** [comment]
I think that is a great idea. I already get those on my Q7  running flight deck and they aew really useful. The OSD needs a major overhaul to make it easy to add new fields.

**Comment by bortek** [comment]
Not right now. In the future it will be possible to write add-ons with own features. Will close it for now.
