### ISSUE TITLE
Using Sony camera with WFB

### ISSUE THREAD

**Issue by myeabhishek** [bortek/EZ-WifiBroadcast#150]
I want to use Sony camera with WFB. How can I go about it?

I have read that HDMI input auvidea has frame rate limitations. My camera supports output HDMI at 1080p 24, 30 fps.

Should I go for a HDMI capture device or is there any other way?

**Comment by bortek** [comment]
You can read more about what you are asking in the wiki section. There it also states which cameras were tested by users. Take a look there. You can also ask people on projects forum page. 

I personally have auvidea but it does not work with my Samsung nx500 because camera only supports 60fps hdmi out. 

Please close the issue when you feel you got the answer you wanted.

**Comment by myeabhishek** [comment]
Can you please link me to this forum page? It will be of great help. Thanks.

**Comment by bortek** [comment]
Sure thing. Here you go.

https://www.rcgroups.com/forums/showthread.php?2664393-EZ-WifiBroadcast-cheap-digital-HD-transmission-made-easy%21/page183

Search first the thread, maybe you find someone mentioning your camera. If not then post a question.

Good luck.

**Comment by myeabhishek** [comment]
Thanks Bortek. I have one final question. Your wiki says it only supports an fps of 30, 40, 48, 59.9. However, my camera supports only 1080p24fps. I am using it with auvidea. 

Will your WFB support 1080p25?

**Comment by bortek** [comment]
Those resolutions you see is for HDMI out on the raspberry pi for connecting the display for example. 

In case of Auvidea it connects to the camera INPUT on Pi and then you connect your Sony camera on the Auvideas input. If you already have Auvidea then it is just to test it.

**Comment by myeabhishek** [comment]
Hello Bortek,

I am able to get camera input on the pi. However, when I use it with WFB, the feed stops on rx after a few seconds and the following error appears:
mmal: No data received from sensor. Check all connections, including the Sunny one on the camera board

Please help with this error. I have raised a new issue #152 for this as well. I can close this one.

**Comment by myeabhishek** [comment]
This has been resolved.
