### ISSUE TITLE
Raspberry pi zero W, wifi adapter don't initialize

### ISSUE THREAD

**Issue by JRicardoPC** [bortek/EZ-WifiBroadcast#153]
Hello,
I have a big problem when I try to use Raspberry pi zero W, and is that the wifi adapter is not enabled, I edit file / etc / network / interface and /etc/wpa_supplicant/wpa_supplicant.conf to enable the wlan0 interface, but don't work. Does anyone have the same problem and how can I solve it?

**Comment by bortek** [comment]
Please post your question on the forum page. thanks.
