### ISSUE TITLE
Updating and maintainng the Wiki

### ISSUE THREAD

**Issue by careyer** [bortek/EZ-WifiBroadcast#165]
**This thread is to collaborate and make decisions on parts of the wiki.**

Please feel free to jump in for a topic here:  
[**Topic Assignment:**](https://docs.google.com/spreadsheets/d/1o-zk3RvxrfGni4EYF-C5TQYLIx2TO9t_FtJvEVsTzzU/edit#gid=0)

Please track changes (and Quality Controls) in the EDIT field:  
![Edit_Message_Field](https://raw.githubusercontent.com/bortek/EZ-WifiBroadcast/develop/wiki-content/Git_Issues/Edit_Message_Field.JPG)

**Comment by careyer** [comment]
Added: https://github.com/bortek/EZ-WifiBroadcast/wiki/RC-:-RC-via-MAVlink
May I ask some native speaker to do a Quality Ceck. Thanks

**Comment by RespawnDespair** [comment]
@careyer not a native speaker, quickly read it and fixed some minor spelling mistakes. Looks great! Well structured and clear!

**Comment by careyer** [comment]
@RespawnDespair  : Merci! =)

Added: https://github.com/bortek/EZ-WifiBroadcast/wiki/RC-:-regular-RC-protocols
Maybe also give that a try!

May I kindly ask to also add the "Quality control" to the changelog (see 1st post) - just for good practice Thanks!

**Comment by RespawnDespair** [comment]
@careyer Done, again very clear information.

**Comment by bortek** [comment]
Fixed a typo otherwise looks good, maybe history part is irrelevant but never mind.

**Comment by careyer** [comment]
Put together a neat wiring diagramm for the RC- and bi-directional telemetry Wiki section:
![Wiring](https://raw.githubusercontent.com/bortek/EZ-WifiBroadcast/develop/wiki-content/RC_RC%20via%20MAVlink/EZ-WifiBroadcast_PixHawk_Pinout_sm.jpg)

**Comment by careyer** [comment]
Here we go "FC Parameters"-Section finished: https://github.com/bortek/EZ-WifiBroadcast/wiki/RC-%3A-FC-Parameters/_edit

Would somebody please proofread? THX

**Comment by bortek** [comment]
corrected, good usage of abbreviation :O e.g. Flight Controller (FC)

**Comment by careyer** [comment]
Thank you very much... this has also been overhauled:
https://github.com/bortek/EZ-WifiBroadcast/wiki/Expert-:-OSD-MAVLink-message-types

**Comment by htcohio** [comment]
I brought up a question on rcgroups about the SR1 parameter refreshing rate being set to "0" as per your instructions.

Correct me if I'm wrong but isn't that the mechanism by which parameters are sent to the ground station side for GCS mp or app? 

Without it the parameters can't download and you cannot use the full function of the app.

Ot Am I wrong?

**Comment by careyer** [comment]
@htcohio : Let me quote the new [Wiki  page on this topic](https://github.com/bortek/EZ-WifiBroadcast/wiki/RC-:-FC-Parameters)

> In order not to transmit telemetry data too often over our radio link, we have to select just the necessary data (the right subsets of information) and at the same time find a good compromise on how often this data should be send and thus be updated. The following parameters have to be found working very reliably:

These settings are just for the proactive streaming (push) of the FC.  The information subsets seleteced (SRx_Parameter/Buckets) just contain enough information to happily populate all the OSD elements. Also refer to here: [OSD MAVlink message types](https://github.com/bortek/EZ-WifiBroadcast/wiki/Expert-:-OSD-MAVLink-message-types). This can also be understood as a kind of news subscription that the OSD has to constantly get the right information without asking for it --> i.e. all SRx_Buckets that contain no relevant data for the OSD can be set to 0 and thus safe bandwidth.

These settings have nothing to do with the GCS requesting (pulling) parameters and settings from the FC. The FC will answer to any request the GCS sends. I hope this clears the fog a little.

**Comment by bortek** [comment]
> Thank you very much... this has also been overhauled:
> https://github.com/bortek/EZ-WifiBroadcast/wiki/Expert-:-OSD-MAVLink-message-types

Done

**Comment by bortek** [comment]
@careyer you can write the comment in "Edit message" field when updating Wiki page instead of adding changelog text to the Excel file. I think it's easier so.

**Comment by careyer** [comment]
@bortek : Sure! Way easier. just wasn't sure if the edit message would be visible for regular users/vistors. Obviously it is not! One more thing learned :+1:  (Will delete the changelog in 1st post then)

**Comment by pilotnbr1** [comment]
> Added: https://github.com/bortek/EZ-WifiBroadcast/wiki/RC-:-RC-via-MAVlink
> May I ask some native speaker to do a Quality Ceck. Thanks

Read through it- looks good! I can help smooth a few grammar/spelling issues out this weekend. Your English is amazing, there is no way I could write anything like that in Deutsche!

**Comment by htcohio** [comment]
@Careyer,

When you have a chance, could you please check your SRx_Paramater to
confirm my same results? I think you'll see that it automatically changed
to 10 by itself.

SRx_PARAMATERS TEST

*This is been brought up several times and I myself was getting confused by
the conflicting results.  Assuming all of these results are verified, the
ardupilot people should probably be notified as well to avoid confusion.

As for the parameter setting being "0" or "10", I believe that the link to
the official ardupilot page is intended for people who are using a Serial
port to stream live Telemetry data for a purpose other than bi-directional
communication or other use that does not actually request the parameter
list.

I made a 12-minute extremely boring video where I tested the following:

1. I set srx_pramater to "0" and rebooted..

Result>> Parameters loaded on the ground side just fine but, when I went
back to check those changed values, to my surprise, it had automatically
reverted back to a value of "10". I tried this twice with the same result.

2. I set srx_pramater to "1" and rebooted to see if it made any difference.

Result>> Yes, the initial parameter download process took roughly 10 times
as long as it did when it was set to 10.

3. Finally I set SRx_param to "5" and by this point as expected, it took
about twice as long when compared to a setting of "10".

So, in conclusion, "assuming that these results would be the same between
all recent versions of Ardupilot" a setting of "0" Hz automatically and
permanently changes back to 10 once it is called upon.

This particular setting does not send continuous data to any device, it is
only sent during initialization of your GCS program on the ground i.e.
(Tower, qgroundcontrol, Mission planner.....)

I hope this helps get us one step closer to Borg perfection 😀

Video test
https://youtu.be/P38TBPq0QK4



On Oct 18, 2018 4:26 PM, "careyer" <notifications@github.com> wrote:

@htcohio <https://github.com/htcohio> : Let me quote the new Wiki page on
this topic

In order not to transmit telemetry data too often over our radio link, we
have to select just the necessary data (the right subsets of information)
and at the same time find a good compromise on how often this data should
be send and thus be updated. The following parameters have to be found
working very reliably:

These settings are just for the proactive streaming (push) of the FC. The
information subsets seleteced just contain enough information to happily
populate all the OSD elements. Also refer to here: OSD MAVlink message types
<https://github.com/bortek/EZ-WifiBroadcast/wiki/Expert-:-OSD-MAVLink-message-types>

These settings have nothing to do with the GCS asking (pulling) parameters
and settings from the FC. The FC will answer to any request the GCS sends.
Does this become clearer now?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bortek/EZ-WifiBroadcast/issues/165#issuecomment-431148233>,
or mute the thread

**Comment by careyer** [comment]
@htcohio : Thank you for the video... it wasn't boring at all! :+1: 
Because of your first hint on this (not long ago in RCgroups) I have tested this of course thourougly ;-) It works flawlessly and as intendent. There is no bug with Ardupilot/Mission Planner software writing the SRx_Parameters. (so to say: whatever value I set it stays the way it is supposed to be)

You must please(!!!) stick to my tutortial word by word: 
* Use Mission Planner (not QGroundControl, APM Planner or something else)... 
* Use direct USB Connection PC<->Pixhawk (not WiFi or Ethernet through WBC or something else). 

In your video you are connecting via EZ-WiFiBroadcast and such through MAVlilnk v1. 
Forgive me for stressing this again: 

**MAVlink v1 does not contain all command extensions and message types to reliably change settings on the drone!** 

You cannot even just download all parameters. Nor does it respond to a simple "LAND" flight-mode change from the GCS. So the failure in  persistently uploading/changing parameters is not surprising me at all. :hankey: 
I hope this impressively illustrates what unnecessary and confusing error situations we are prone to see all day long when we release this to the wild. It is absolutely necessary to fix this by getting rid of the old legacy protocol and switch to it's latest incarnation v2.3 :-)

All the world is talking MAVlink 2 nowadays just we sit in between "Lost in Translation" ;-)
This depicts your exact situation here:
![LostInTranslation](https://raw.githubusercontent.com/bortek/EZ-WifiBroadcast/develop/wiki-content/Git_Issues/LostInTranslation.JPG)

Connecting the GCS and FC directly via USB both are talking plain MAVLink v2 without loss in conversions and hickups due to missing message types.

**Comment by htcohio** [comment]
Hey, I fully understand that and all of those test results were verified with USB Mission planner and PC with mav v1 and v2.

I simply used qgroundcontrol because it was easier to visualize everything on the video.

I also discovered yesterday that, if I set "0" on my pixhawk (arducopter) with laptop on Tarot Hexacopter, it does not automatically change it back to 10 like it did in my video. And nothing loads or works with either Tower or Mission planner...

I just want to make sure that we have it right.

**Comment by careyer** [comment]
Sure! I will have a look into it again... but I have it on two of my copters and it works without problems.

**Comment by careyer** [comment]
Another page for the wiki... could someone proofread please.?
Pictures can be clicked to view in bigger size.
https://github.com/bortek/EZ-WifiBroadcast/wiki/RC-:-Reliable-Setups

Any other known WBC RC-Controllers, maybe?

**Comment by Yes21** [comment]
**@ALL**
In the "Ground Stations" section (QGroundControl and Tower), I can read that the UDP video stream port has to be set to 5000. 
But in the wbc config file it is set by default to 5600 !!
5600 is working for me ...

**Comment by bortek** [comment]
@careyer corrected. What a neat and sexy controller you have built :) I like it.

**Comment by pilotnbr1** [comment]
@careyer I read your latest page. Proof read and one minor correction. Well written and nicely presented! We definitely need some more builds added in the basic category. Your build is perhaps the ultimate wbc build and thus unattainable for most.

@Yes21 yes there was some back and forth with ports at one time. I believe Rodizio did some coordinating with Consti of the Fpv vr app. Pretty sure for the most part Consti followed Rodizio’s lead.
https://www.rcgroups.com/forums/showthread.php?2873827-FPV_VR-Ultra-low-latency-for-FPV-Virtual-Reality-Android-App/page3

**Comment by careyer** [comment]
@bortek : Thank you very much... I am sorry for the many typos. This just happens when you fill the sections like a madman. ;-)

@pilotnbr1 : Thanks. The controller is basically just a Pi, a Pi display and two gimbals thrown together into a enclosure! Makes the preparations to go flying and the actual flight a breeze. :+1:

**Comment by careyer** [comment]
@Yes21 / @All 
Once I played arround with displaying the Video in the Mission Planner HUD. As far as I can remember Mission Planner has a fixed port which cannot be changed (whereass QGroundControl etc. have settings that can be modified). Maybe we should stick to the MP port so that all GCS are compapatible? I don't remember the port anymore and how I managed to get this working... though

**Update:** Regarding to [this](https://discuss.ardupilot.org/t/udp-video-stream-in-mp-hud/16003) MP is listening to 5600. I think that was why rodizio changed it from 5000 to 5600 as far as I can remember. I talked with him about that (I believe)

**Comment by careyer** [comment]
@htcohio : I have tested the Serial Parameter thing again with two insights:

1. SRx_Params and SDx_ADSB must not be 0 in order to allow for full bidirectional telemetry. These parameters are not needed for OSD-Telemetry or RC but they are needed to successfully connect the GCS. (Good values are SRx_Params=10 and SDx_ADSB=5 - I will edit the Wiki accordingly) So in this regard you were right. :-)

2. The problem that your modified parameters were not saved and almost every time reset to default is definetly a MAVlink version inconsitency problem. I did a full-featured testseries with both "genuie 1.6rc6 (MAV1)" and "dino.de 1.6rc6 (MAV2)" image.
Here are the results: 
![Mav1vsMav2.JPG](https://raw.githubusercontent.com/bortek/EZ-WifiBroadcast/develop/wiki-content/Git_Issues/Mav1vsMav2.JPG)
I also noticed that with MAV2 it almost does not matter at all how much telemetry data is being sent. Whereas MAV1 would likely suffer hickups when transfering too much telem data - there seems to be no more problem at all. All is as fast and reliable as via a USB cable directly plugged in.
So in this regard I was right ;-) 
**This is a big deal. Absolutely all GCS functions work :100:%  flawlessly with MAVlink 2.3. This is so much fun and no longer a pain in the ass.**

BTW: I was also able to figure out how to get the Video stream right into Mission Planner and have it overlayed with the HUD. Took me about 3hours so figure that out. It needs a bit of playing arround with GStreamer on the command line and only then start Mission Planner. This is sooo cool! :+1:

**Comment by pilotnbr1** [comment]
@careyer I noticed an oversight in the FAQ I wrote regarding supported rc protocol. I had left out MSP. Thought I would give you a reminder since you are writing the rc docs.

**Comment by careyer** [comment]
Luke, Thank you for pointing this out. Does 1.6rc6 still support MSP? I think I remember someone saying it was deactivated for some reason?

Btw: I never worked with MSP? What exactly is it? Telemetry or RC protocol or both? All I know is that it is somewhat related to MultiWii. Is that right? 

Cheers

Von meinem iPhone gesendet

**Comment by Yes21** [comment]
**@careyer** For the OSD section, do you remember [this post](https://www.rcgroups.com/forums/showpost.php?p=40051357&postcount=5408) from you on rcgroups ?
It could be nice to use it ... ?

**Comment by pilotnbr1** [comment]
@careyer all very good questions. I have many of the same. I’ll tell you everything I think I know which isn’t much. MSP stands for message send protocol, and is also known as Multiwii. Apparently it is both a telemetry protocol and radio control protocol. MSP is the native language of INav. From what I remember talking to Rodizio, wbc only supports msp v1 and currently msp is on v2 (not 100 percent sure).
Looking at the .profile code here on github, is what made me remember msp. The rc function does recognize msp as an option. Not sure if it works though. I think this needs to be escalated and investigated...

**Comment by careyer** [comment]
@pilotnbr1 : Yes we should verify first if MSP (i think it was "MultiWii Serial Protocol") still is supported before we add any information to the Wiki about it. I also remember that it caused some weird problems due to the old MSP v1 version. (very similar to the Mavlink stuff).

**Comment by careyer** [comment]
@Yes21 : Sure! please go ahead and add that to the according Wiki section.... I could really need some helping hands with the Wiki.

**Comment by careyer** [comment]
@All : I cleaned up the mess under [EZ-WifiBroadcast/wiki-content/](https://github.com/bortek/EZ-WifiBroadcast/tree/develop/wiki-content) .

Please keep some order and if not yet existent create new folders according to the wiki structure for your content.

**Comment by bortek** [comment]
👍

**Comment by Yes21** [comment]
> Sure! please go ahead and add that to the according Wiki section.... I could really need some helping hands with the Wiki.

**@careyer** I've added up to 26 numbers on your rcgroups snapshot, and have began to fill the number explanations with your text.

**@ALL** Could you please help to explain all the OSD informations I've identified on the snapshot ?

**Comment by RespawnDespair** [comment]
@careyer 
> 2\. I did a full-featured testseries with both "genuie 1.6rc6 (MAV1)" and "dino.de 1.6rc6 (MAV2)" image.

Where can i find this image? I want to try to merge this with the builder now the basics seem to work. No sense in publishing an image if we know mavlink is this broken...

**Comment by careyer** [comment]
@RespawnDespair : I linked it several days ago for you guys here: https://github.com/bortek/EZ-WifiBroadcast/issues/155#issuecomment-429423820

It basically is a 1.6rc6 plus added features:
- Mavlink 2,3 instead of the outdated Mav1
- GroundPi actions triggered by Joystick, e.g. OSD on/off or switch OSD screens (search for "switches" in .profile)
- AirPi actions (GPIO) triggered by Joystick (search for "airswitch" in .profile)
- Flir1 Thermal camera support (search for "###" in the .profile - multiple ocurrences)
  also there are some driver things needed ... can be found in /root/flir.... and /root/v4l2loop....

In case of any quetsions... you are welcome!

**Comment by bortek** [comment]
@Yes21 you have number 12 used twice on the image, check right side corner. Other than that: 


5 RSSI signal?
14 GPS Direction in degrees
15 GPS Speed
16 GPS height (MSL)
17 Vertical speed (lift/sink)
20 Distance to Home/Starting point
21 Latitude
22 Longitude
24 Aircraft's Batt voltage
25 Aircraft's Batt consumption

**Comment by careyer** [comment]
12 AirPi  CPU load and Temperature
13 GroundPi CPU load and Temeprature
23 Fligthmode

**Comment by pilotnbr1** [comment]
I went through the whole wiki and applied the AirPi and GroundPi terms. I did little to the configuration options page as it reflects the current variables in the project which still use rx and tx as names.

Additionally I am going to cleanup the WiFi adapter page with a table. The proposed columns are-

Name / frequency range / output power / range / notes

**Comment by careyer** [comment]
@Yes21 : very well done. Your help is much appreciated:-)

Von meinem iPhone gesendet

**Comment by Yes21** [comment]
**@careyer** : Thanks.
I will correct the image, and add the explanations you and **@bortek** gave.
Thanks in return for your help ...

**Comment by pilotnbr1** [comment]
Added a table to the supported WiFi adapter page. Double check me for accuracy, I was going cross eyed with the markup. 

I left all of Rodizio’s original page and notes for now, but I propose the rest of the page be condensed so as not to be too redundant.

Personally I like tables because it organizes information and makes comparisons easier. I would like to add more tables to other parts of the wiki to further organize. Thoughts?

I think a big goal is to remember this is EZ so let’s keep it simple and approachable.

**Comment by careyer** [comment]
@pilotnbr1 : Very nice... I like the idea of the table...
I added a collum "RC" since only the Atheros chipsets are afaik capable of doing RC uplink. (I am not sure what is the technical reason for that)... I also added the WifiStation EXT

**Comment by pilotnbr1** [comment]
@careyer added aw nu-137 afaik it works. Cant find details on it as no sellers I find post complete specs.
Yes RC is a good idea. Some content from that wiki page would be applicable to the new antenna page.
What other WiFi are we missing?

**Comment by Yes21** [comment]
**@careyer** 

> I added a collum "RC" since only the Atheros chipsets are afaik capable of doing RC uplink

I didn't knew that.

Big question : is this also true for telemetry uplink (because RC=mavlink  as to be set for up telemetry) ? 
I can't make it work with RT5572.

**Comment by careyer** [comment]
@Yes21 : That might verry well be the case. I am not sure though. All I know is that the RaLink cards are not capable to be used for RC. Since RC is just part of the Uplink-telemetry stream.... yeah well possible.

@ALL : Here you go with the new Mission Planner and inject HD-Video directly to the HUD page:
https://github.com/bortek/EZ-WifiBroadcast/wiki/GCS-:-Mission-Planner
It was a real pain in the ass figuring this HUD part out. Please proofread and tell me your thoughts...

Please let me emphasize again that anybody is welcome to overhaul and contribute to the Wiki. This is so much work we can only do it together.
@htcohio : Maybe you can make a go for the QGroundControl section... for all plattforms (PC / MAC / Adroid / iOS) in a similar style?

**Comment by Yes21** [comment]
**@careyer** 

> That might verry well be the case. I am not sure though. All I know is that the RaLink cards are not capable to be used for RC. Since RC is just part of the Uplink-telemetry stream.... yeah well possible.

If it works only with old atheros chipset, the scope of this project is becoming very reduced !

I could see the uplink telemetry work only one time : with the last "russian image", and my rtl8812/14au boards ...

**Comment by Yes21** [comment]
**@pilotnbr1** Thanks, that's great.

Perhaps could you also add a column to inform users if the board is always manufactured or not ... ?
This is a very useful information for new users.

**Comment by careyer** [comment]
@Yes21 : Totally agree... I have no idea what causes this limitation and it would be great to get rid of it. Is something missing from the driver maybe? Or was Rodizio just not able to make it work? We should investigate into this further. It will be a much bigger leap forward than supporting the RPi3B+ ... which is also a must as we all agree upon. However this will really bring more features with it.
Right now only the Atheros cards can do RC-control and (very likely) your observation refering to Uplink telemetry not working on your RaLink cards is related to this as well, i.e. RaLink cards are very limited right now.

Maybe this has something to do with it? There is a file called.  [EZ-WifiBroadcast/wifibroadcast/rcrx.c.ignore-ralink](https://github.com/bortek/EZ-WifiBroadcast/blob/develop/wifibroadcast/rcrx.c.ignore-ralink)

So bottomline for now is: Atheros AR9271 is by far the most capable chipset at the moment. Highest TX power, 2,GHz good penetration and range, and all features of an AIO system working.

**Comment by careyer** [comment]
@All : Changed all ":" characters in the Wiki Pagenames to "~" because the colon prevented the Wiki from being cloned locally via GitHub Desktop (":" ain't a allowed character on windows file systems). Also changed every link througout the Wiki

**Comment by htcohio** [comment]
Hey,

I'm really sorry I haven't contributed a thing to the wiki but I've been
compiling notes photos and info.

////////////////////////////


Honestly, there are a few details that arent very clear such as the mission
planner side but Careyer, great job sorting through that part!  Overall I
have been Gathering little pieces of valuable information so that it can
all be integrated with the wiki and, this has been our busiest time of year
right now so work has also been kind of hectic.

////////////////////////////

Also, some of my testing with the RPI 3b+ seem have instability with the
power for some reason and the fix is to direct solder the 5V regulator to
the USB pins as well as the main power pins even on the ground...

////////////////////////////


**@yes21 as for the rt8812/14AU chipsets I myself have been a little
unclear on this, I've been reading back through the posts from Rodizio more
than a year ago trying to find some relevant info as to why the RC is
limited to atheros chipsets.

When I tested the Russian image with 8812 I had trouble pulling video but I
had Telemetry and RC control.  I think it may have something to do with
multicasting but I haven't found any solid information....

**Comment by pilotnbr1** [comment]
> **@pilotnbr1** Thanks, that's great.
> 
> Perhaps could you also add a column to inform users if the board is always manufactured or not ... ?
> This is a very useful information for new users.

I agree. The only thing is that the WiFi adapter table is growing so wide that it will soon not correctly fit 😆 at least on an iPad display. Curious with other browsers/resolutions/devices if we can add another column. Perhaps delete the 2.4ghz column since all adapters support it.

One thing with adapter availability I have never seen any go away completely with eBay...

**Comment by careyer** [comment]
@htcohio : have you proofread the new wikipage?
https://github.com/bortek/EZ-WifiBroadcast/wiki/GCS-:-Mission-Planner or somebody else?
Running the videofeed through the HUD is really fun and awesome for FPV. You should give it a try.

**Comment by htcohio** [comment]
Hello, yes I have.

I haven't tested mission planner yet but for QGC i am not sure we need port
14550 setup.  As a matter of fact, when connected over 5g hotspot I do not
need any port except for the port 5000 or 5600 under general config tab.

Setting 14550 under com ports seems to create instability for me but, I
might be missing something here so I should have an update tonight.

**Comment by pilotnbr1** [comment]
Updated the Home page and Release Page.

All old links to images are now with the details about each release on the Release page.

Added the Logo to the home page.

TODO in my opinion

Home page needs some sort of HIGH quality short advertising video
Home page needs more explanation of each feature with graphics or images of EZ features-
    How easy it is to setup 
    HD video and OSD
   Telemetry 
    RC
    3rd party compatibility 

Tweaked the instructions on the home page. Not sure if those instructions on the home page should go to the quick start page or just eliminate the quick start page. Thoughts?

**Comment by careyer** [comment]
@pilotnbr1 : Neat! That looks nice! Good job! Agree with your propositions for the Home-page
However 1.6rc6 is not the latest stable version... it is a release candidate. We should also maybe keep the link to the last final version which is 1.5

@htcohio : Thanks you! Yes QGroundControl is a whole different story. It is rather easy to get this one going.

**Comment by htcohio** [comment]
Yeah, you able to confirm that you can get qgroundcontrol to work without
port 14550 used?

For me it works with hotspot and usb.

It also works on 5600.

**Comment by pilotnbr1** [comment]
True regarding release candidate vs stable. Is anyone actually running 1.5? In my testing 1.6rc6 seems very stable. To me this seems to open some questions regarding when how a release goes from a candidate to a stable release- I don’t really know! I am usually an end user on this kind of stuff and hack it for my own use... I need to get smart on this
Putting 1.5 back in place now

**Comment by careyer** [comment]
Thanks @pilotnbr1.  I have asked khomyakk if we can use some spinets of his 31km record flight for the intro video. Hope he is okay with that. I have the whole raw material and the flight is awesome... very clear image, no wiggles and shakes... just beautiful. We could create a nice trailer out of it if somebody is skilled at Finalcut or Adobe Premiere. 

@htcohio - I have not used QgroundControl much other than noticing telemetry works right out of the box at startup and video needs to be changed to port 5600. (it needs rtp configured in wifibroadcast_1.txt though I believe). It would be great if you could do a writeup on this section since you have more experience using it. Thanks!

**Comment by htcohio** [comment]
@careyer,,

Yes I am definitely posting a write-up about that.

I have also perfected the FRsky taranis all-in-one wfb controller power directly from the Jr Main V+ pins.

A 3s lipo mod is needed since the stock taranis NiMh battery voltage sags too much for the regulator to put out a stable 5 volts.  I also found a nice 3D stl file to expand the battery Bay so that everything stays nice and tidy.

That combined with a good 5v voltage regulator allows everything to be turned on and off through the main power taranis switch :)![](https://i.imgur.com/g1rdsTX.jpg)

![](https://i.imgur.com/tkepzP6.jpg) 

![](https://i.imgur.com/u7ah3h8.jpg)

![](https://i.imgur.com/5T7kV8y.jpg)

**Comment by bortek** [comment]
Feel free to start drafting Quick Start Guide if you feel for it. I think we will then feel which parts from the existing pages can me merged into it like pilotnbr1 suggested. I will now try to focus on continuing the landing page.

**Comment by htcohio** [comment]
I have PowerDirector Pro and I've been familiarizing myself with it again.
Please share the link to the video.

I would also like to Begin work on the instructional videos with the quick
start guide.

I'll basically document the initial setup and soldering, software for
writing the image and tips.  Once I have it professionally put together you
guys can take a look at it and make sure it looks good

I would actually like to get started on that part of it right away once I
finish the write-up for Q Ground Control, wifi card tests and the antenna
tests....

**Comment by careyer** [comment]
@all : khomyakk  answered and gave permission to use footage from his 31km record flight for the "Introduction video". :+1: That's very generous. I am just wondering who can make this happen and is skilled at video editing and where I could upload the raw footage (6GB). We should also brainstorm what the content of the video should be. Maybe open another issue on that?

**Comment by bortek** [comment]
Uploading is not an issue, I can provide space for hosting it. But editing a video is like a separate task taking many hours. Of course it depends on the content and if it's plain editing from this timestamps to this and then fitting with music or more in depth stuff. I have done editing in the past but think someone else can do it better. 😁. Perhaps @richardbmx knows someone who can help?

**Comment by Yes21** [comment]
**@bortek** 
I want to ad a "EZ-WBC Logo" folder in "wiki-content", but don't know how to do it !
It will be for storing all logo sources from @richardbmx.

Thanks for your help.

**Comment by careyer** [comment]
@Yes21 : for this reason I also uploaded all my pictures from the wiki to the develop branch. There you can easily upload files.... for creating a new folder you just have to type in the full path and create a dummy file in it ..... e.g. /wifibroadcast/**Logos/dummy.txt**

Lemme just do it for you =)

**Comment by Yes21** [comment]
@careyer : Thanks I could do it.

**Comment by pilotnbr1** [comment]
Once the logo is uploaded I think we can close the Logo issue

**Comment by Yes21** [comment]
All is here : [https://github.com/bortek/EZ-WifiBroadcast/tree/develop/wiki-content/EZ-WBC%20Logo](https://github.com/bortek/EZ-WifiBroadcast/tree/develop/wiki-content/EZ-WBC%20Logo)

**Comment by careyer** [comment]
Close the Logo issue... not this one ;-)

**Comment by Yes21** [comment]
Sorry ...

**Comment by careyer** [comment]
Not a problem! ;-)

**Comment by Yes21** [comment]
**@ALL**
I've finished to update the "[**Advanced/Telemetry & OSD**](https://github.com/bortek/EZ-WifiBroadcast/wiki/Software-~-Advanced-~-Telemetry-&-OSD)" wiki page.
Please, have a look at it, and don't hesitate to make corrections.
Thanks.

**Comment by bortek** [comment]
@Yes21 I saw you managed with the dir creating!  I checked the wiki, it looks really good, could not find any spelling errors. Well done!

**Comment by careyer** [comment]
@Yes21 : Nice work! Looks perfect...
You should however consider to use [this graphics](https://raw.githubusercontent.com/bortek/EZ-WifiBroadcast/develop/wiki-content/RC_RC%20via%20MAVlink/EZ-WifiBroadcast_PixHawk_Pinout_sm.jpg) since the 5V line isn't needed and also it does not fit to the 2nd picture you show (only 3 lines connected). ;-)

The other picture also fits nicely the Pi Zero used in yout second picture.
You might want to consider adding yourself to the google spreadsheet in the 1st post?
It is nice to have some help! =D

**Comment by pilotnbr1** [comment]
@Yes21 very nice work!

**Comment by Yes21** [comment]
@careyer : Thanks ! Done.

**@ALL**
Please could you also help me with these 4 items I don't know ?

_7 | ?
8 | ?
19 | don't understand difference with 16 ...
20 | don't understand difference with 17 ..._

Thanks.

**Comment by bortek** [comment]
I am sure 19,20 is Airspeed and Barometric Altitude but you must have pressure sensor for baroalt and for airspeed there is a different sensor. I don't think anyone actually uses it
I listed it out from here which I think is used in 1.6. Look 
https://github.com/wowi69/EZ-WifiBroadcast/blob/develop/wifibroadcast_osd/render.c


6,7,8 must be different bitrates, like measured and received . You can see there are 3 bitrate variables defined 
https://github.com/wowi69/EZ-WifiBroadcast/blob/develop/wifibroadcast_osd/render.c#L555

**Comment by Yes21** [comment]
@bortek : Many thanks :smile: 
7 & 8 are the 2 zeros (0/0) on the third line. 
I don't know what they are for ...

**Comment by careyer** [comment]
Added a neat way on how to shrink Pi-Images to the least possible size (with filesystem auto expand on 1st boot) to the Expert section: https://github.com/bortek/EZ-WifiBroadcast/wiki/Expert-%7E-Shrinking-Images

**Comment by Yes21** [comment]
@careyer 
Many thanks for that !!
It's very useful. I will ask @RespawnDespair to add it to his building script.

**Comment by rodizio1** [comment]
I think this shrinking thing should be removed from the wiki, all it does is adding confusion for the end-user.

**Comment by careyer** [comment]
ok... will remove it (at least from the menu...) ... should we remove the "Mounting Images" (@bortek 
) or other content as well? It is in the "Experts" tab though: people should be aware that they are tinkering with the guts here ;-)

How about moving it to the developers corner?

**Comment by bortek** [comment]
I don't think we should remove it as this is the knowledge that at least we ourself are using. Some of the advanced users will likely also find it useful. 

I think what rodizio implied was that we might get unneeded questions due to it. 

Perhaps instead we should clearly write on the pages(s) that this is an expert or danger territory and they should know what they are doing and we will not be able to help if they break things.

**Comment by careyer** [comment]
I moved this content to the "Developers Corner" section. Now it should be pretty much clear not to mess with these things if you do not know what you are doing ;-) @bortek : But this is a good idea. Can you add a word of caution to those pages? Merci!

**Comment by rodizio1** [comment]
Actually I don't see _any_ valid usecase for this, not even for ourselves.

What would be the usecase, with the current (i.e. too large root partition) image?
- Shrink it, then burn it to sdcard, just to have it unshrink itself right on the first boot?

What would be the usecase with a later version (i.e. not too large partition) image?
- There is nothing to shrink.

**Comment by careyer** [comment]
Ok will remove it then.  My heart's not on this. Sorry for the confusion.

**Comment by Yes21** [comment]
I think it's not a good thing to loose these informations.

It was the only place where I could find a clear explanation on how to mount an img file, and where I could discover the pishrink script ...

And now, I can't remeber how to mount my images  )-:

**Comment by bortek** [comment]
- Copy image to my home NAS where I have all my other images. 
- Upload image faster, and download faster for others.
But yeah whatever and never mind :) it's not worth it :)
