### ISSUE TITLE
1.6 suggestions

### ISSUE THREAD

**Issue by geofrancis** [bortek/EZ-WifiBroadcast#17]
as well as the main telemetry link that the osd works from, having some more transparent uarts would be very useful for people with gimbals, RTK gps, multiple telemetry links like frsky and mavlink or other devices that use serial ports, currently the only solution out there is to have multiple telemetry radios. wifibroadcast video uses so much bandwidth that 3x 115200 serial links should be barely noticeable 

In theory it could also be used for transparent RC links. then you wouldn't have to worry about generating the rc output, you should just need the correct baud rate for the protocol so what comes in goes out. for failsafe you just stop the output simulating rc disconnect, most flight controllers will just see that as out of range and failsafe without having to configure anything.

sbus is 100,000
dsm and sumd is 115200

just have something in the config like:

TX
telemetry/osd port: /dev/ttyUSB0
baud1: 57600 
serial2: /dev/ttyAMA0
baud2: 100000 (for sbus, 115200 for DSM, SUMD, MSP or 57600, 38400, 9600. )
serial 3 /dev/ttyUSB1
baud3 115200

Rx 

telemetry/osd port: /dev/ttyUSB0
baud1: 57600 
serial2: /dev/ttyS0 (or "USB" for MSP)
baud2: 100000  (for sbus, , 115200 for DSM, SUMD,MSP or 57600, 38400, 9600. )
serial 3 /dev/ttyUSB1
baud3 115200

Another idea would be to use different wifi adapters for video and telemetry, then you could have your data on 2.4ghz and video on 5ghz or just on different channels and it would avoid the problem of having to stop the video tranmitter to receive.

because each serial connection can have its inputs and outputs setup and is standardised it would be very flexable, you could have 3 telemetry links or theoretically up to 48 channels using 3 rc links, plus there is no real limit to the number of serial links apart from the number of usb ports you have and bandwidth, but if you got the data on a different adapter it would be a lot.

**Comment by geofrancis** [comment]
i found this and wondered if it would make it easier to impliment multiple serial ports

http://www.usriot.com/p/modbus-tcp-ethernet-ip-modules/

**Comment by Montilien** [comment]
Hi, congratulations for this good work. Did you think to add 3G/4G dongle alternantive for very long range Video, telemetry, and RC???
Best regards
Andre

**Comment by Montilien** [comment]
Hi Rodizio,
Why have you closed my question without any response?????
I think that my question is interesting for many user of EZ WIFIBROADCAST...
Best regards
Andre
