### ISSUE TITLE
unable to open interface intwifi0 in pcap

### ISSUE THREAD

**Issue by Mani17192** [bortek/EZ-WifiBroadcast#176]
Hi,
I am using v1.5 for both TX and RX with Alfa AWUS036NHA  and I am facing a error.
ERROR: unable to open interface intwifi0 in pcap: intwifi0: that device is not up.
But whenever I run the .profile script manually it works like a charm.

**Comment by careyer** [comment]
@Mani17192 : Hi.... the latest stable 1.5 is actually very very old (more than a year).... please try the latest 1.6rc6 and see if the problem persists. Thank you.

**Comment by Mani17192** [comment]
@careyer , I have used 1.6rc6 and I found v1.5 more stable in terms of video feed quality.
Only this little error is disturbing me. Ill be grateful if can you give me some heads up to figure out the root cause like if I can put "sleep" some where in the .profile because so far I have understand that this is happening due to some service which is overlapping the boot or hardware synchronization.

**Comment by maniranjanojha** [comment]
Any update?

**Comment by rodizio1** [comment]
Sorry, 1.5 is too old, won't spend time on that release anymore. It would be nice if you could open an issue though with your findings about the quality being better with 1.5 compared to 1.6.
