### ISSUE TITLE
Incorrect image diagram in Wiki

### ISSUE THREAD

**Issue by pilotnbr1** [bortek/EZ-WifiBroadcast#177]
The tx and rx pins on the pixhawk side appeared reversed in the diagram. I don’t own a pixhawk but after some quick googling the pins on the pixhawk side appeared reversed in this image. The text is correct.

So on pixhawk the green wire should be on left pin and yellow wire on right pin.

![RaspberryPi_Pixhawk_wiring1.jpg](https://raw.githubusercontent.com/bortek/EZ-WifiBroadcast/develop/wiki-content/RC_RC%20via%20MAVlink/EZ-WifiBroadcast_PixHawk_Pinout_sm.jpg)

I removed the image off 2 pages in the wiki. The text was correct in the wiki. Can someone with a pixhawk please confirm the pins?

**Comment by pilotnbr1** [comment]
Pin order on pixhawk as far as I see is left to right - 5v rx tx cts rts gnd

Edit here is an image of telemetry 1 pinout

![9c9f6720-53a0-419e-857d-3011e4e8025a](https://user-images.githubusercontent.com/11220330/47861483-97510800-ddfb-11e8-8d08-977639f37131.png)

**Comment by careyer** [comment]
@pilotnbr1 : No... my diagram is perfectly okay.
Check out the official manual for Pixhawk and the official pinout here:
http://ardupilot.org/copter/docs/common-pixhawk-overview.html

It reads left to right:
VCC | TX (OUT) | RX (IN) | CTS  | RTS | GND 
Just the same order as in my diagram ;-)
Always consult the original documentation. There are a lot of sketchy third party sketches arround.

The image was just misinterpreted by a RCgroups fellow who interpreted the "RX" notation in the image as "connect RX to RX". 

May I kindly ask that you to undo your changes on both wiki pages? ;)

**Comment by Yes21** [comment]
> VCC | TX (OUT) | RX (IN) | CTS | RTS | GND

On PixHack and PixHawk 3 Pro, that's : VCC | RX (IN) | TX (OUT) | CTS | RTS | GND

See the picture (from me) [here](https://github.com/bortek/EZ-WifiBroadcast/wiki/Software-~-Advanced-~-Telemetry-&-OSD).

**Comment by careyer** [comment]
Okay... but we have a Pixhawk1 (not Pixhack or Pixhawk 3) in this diagram and this is VCC | TX | RX | CTS |...
It is the most common FC out there right now...
And you can without any doubt trust the official pinout :-)

You can crosscheck here also:
![grafik](https://user-images.githubusercontent.com/6156251/47863485-acc43300-ddf7-11e8-897c-d80c26b93a37.png)

![grafik](https://user-images.githubusercontent.com/6156251/47863470-a3d36180-ddf7-11e8-9a64-3606a941be99.png)

**Comment by pilotnbr1** [comment]
Ok ill repost the diagram. Pixhawk and clones made this confusing. I will add a large note to the wiki to clarify that the diagram is for pixhawk 1 only. Perhaps we can add diagrams for the other types as well or at least a pinout text.

If I was a new user and bought something other than a real pixhawk 1 I may have made a mistake also and then incorrectly assummed it was a problem with wbc lol

**Comment by Yes21** [comment]
> On PixHack and PixHawk 3 Pro, that's : VCC | RX (IN) | TX (OUT) | CTS | RTS | GND

Sorry ! On P3 Pro it's also VCC | TX | RX | CTS | RTS | GND, like for P1 ... (like on my picture)
