### ISSUE TITLE
Code of conduct and spinoffs

### ISSUE THREAD

**Issue by bortek** [bortek/EZ-WifiBroadcast#178]
I saw there was a spin-off image posted on the RC-groups forum and thus I created this Issue to take a short discussion about it and hopefully clear up eventual misunderstandings. 

It is totally fine if someone forks the code, rebrands it, builds it's own image, website, forum/support page and goes it's own path. This has been done before. 

But if you are contributing within this main project then I think it is NOT ok to make own spinoff and mix it with the main image development and testing process for the following reasons:

- It takes developer's extra time as he/she needs to troubleshoot errors and answer questions created by spin-off code.
- Confuses people on the forum page about which image is which.
- It create unneccessary frustration among contributors as well as users.

Therefore I would like to ask you to respect the work done within open source community.  Once again if you want to make a spin-off please do so but do it outside of this project including forum page.

I will updated code of conduct reflecing the above.

Questions?

**Comment by pilotnbr1** [comment]
I think as soon as an image is made here that has all of the features from the various images, it will temporarily fix confusion. But going forward this is a good suggestion to try and eliminate some confusion and extra work...

**Comment by RespawnDespair** [comment]
You will probably all have seen my post on the rcgroups forum as well, but here i can be a little more direct.

I think the situation could have been dealt with differently, yes, i agree the many different images in the main thread are a distraction, and we need to address that. But i want to be very careful not to repeat the situation we had with Rodizio. 
FlyingW was unaware he wasn't working on anything but the main effort and was trying to be helpful. Justin has always been helpful as well, sometimes i might not agree with has actions, but i've always been able to talk to him about it normally and respectfully.

Posting about such matters in the main discussion thread does not paint a very good picture of the project and the people working on it. My voice has no more weight than any of yours, but i would like to call on everybody to try and resolve any grievances through dm's with the persons involved.

I appreciate everyone working on this project and i really feel we have the potential to make this something great, so let's focus on our goals and not be distracted by issues like this.

Have a great weekend!

**Comment by careyer** [comment]
Thank you @bortek for opening this discussion and thanks @pilotnbr1 and @RespawnDespair for sharing your opinions respectively. 

I totally agree with you Jelle that the RCgroups thread or any official forum is not the best place to dicuss things like that and I am sorry to have posted in a bit of a harsh manner. I've struggled with myself for a long time if i should do so or not (you might notice that my reaction was in no way immediate) and after days of waiting and reflecting things I tried to disarm the words I chose as much as possible but without transporting a message in between the lines.

What you cannot know is that well before we started to kick-off this awesome EZ-Wifibroadcast revival me and Justin had lots of out-of-band communication (PM & Email). We discussed things like involving money (donation/incentivation) and also changing the name of the project.
I will not go into details other than I stated very clearly that I was against both of that and also explained why. Against my skeptisism if all this would turn out for good I asked Boris to invite Justin to the project. Shortly after I learned that Justin had kicked off a donation system overnight without consulting any of us. Also the matter of changing the name of the project was brought up again here on GitHub and the common decision was made not to rename the project. Moreover we decided that we would have a new Logo instead which would help us get more visibility, promote our "brand" and attract new users/developers to the project. Now -as a matter of coincidence- "Open HD" shows up in the forum. @htcohio, I got really mad when I saw this and please bear with me when I say that I do not believe that this was just a coincidence. I strongly believe that this is not how friends should deal with each others trust.  If indeed it really was a coincidence - I say SORRY! but at the same time I want to appeal to you not to counteract our efforts in making "EZ-Wifibroadcast" big and well-known by acting somewhat unreflected. Lots of effort and work goes into this. I still consider you a friend and I do not want to argue with you or have a quarrel. This is also why I will not answer anything to your post on RCgroups and accept the role of the mean person. I can take it.

Just like Boris pointed out I have nothing against the idea that someone sooner or later wants to capitalize on the project by e.g. selling accessories or even offer an off the shelf solution based on EZ-WBC - we can't stop someone from doing so. I just believe (and this is my very personal opinion) that this is not the right way to somewhat covertly establish a new (brand)name on the shoulders of giants who worked increddibly hard to make this all possible. 

Have a great weekend my friends.

**Comment by RespawnDespair** [comment]
Thank you for sharing your reasons, i think i understand everything a little better now. Please know i do not consider you a mean person, quite the opposite. I value you participation in this project greatly. 
I hope we can leave this behind and move forward without any ill feelings.i can't speak for everyone, but i still consider everyone involved as friends and that very much includes you as well as Justin. 

Jelle

**Comment by careyer** [comment]
Thank you Jelle. The last part of my message starting with "@htcohio, ..." was primarily addressed directly towards Justin. I am happy to hear that you don't consider me a mean person! :relieved: Have a nice evening and don't code all night long my friend.

**Comment by Yes21** [comment]
I take a little time to give my own opinion now, because I was/am involved in testing Jelle's building script for 1.6.
Yes, I know I've seen some strange messages on the RCgroups forum. But they didn't interest me, and I didn't want to waste my energy to react against them.
What is most annoying me, is when people are diverging from the subject , and try to speak about something else.
There is here (on the forum and the issues) a few specialists (which I won't name ...) of this behavior.
I hope they could become mindful of it, and stop disturbing the others from their goals.

And now, my friends, let's go further !

Yves

**Comment by bortek** [comment]
Friends I appreciate you sharing your opinions. 

Very thoughtful indeed and I agree that perhaps this could have been done differently. But this time I though it was necessary to bring this up publicly and openly. To vent out our feelings sort to say :) which somehow helps to get to know each other better. Everybody is different but we are all humans and I have a feeling that this will make us stronger as a team. Now let's carry on. Thank you!

Have a great weekend!
/Boris

**Comment by pilotnbr1** [comment]
@bortek @RespawnDespair @Yes21 @careyer I think there are a lot of passionate people here and on rcgroups who think we have something special here. We all want to advance this project into something more. My hope would be that we could all work TOGETHER in the most efficient and TEAM oriented way possible. 

We all know we have limited resources to provide support and development. We have all seen the ups and downs of this project. As a result we are all very sensitive to things we perceive as a threat to further development. In my view one of the biggest threats for WBC is dilution and forking. Having different devs all going off in different directions is not the most efficient way to do things. Even Wolfgang at Dronebridge has a statement saying he doesn’t support forks and he forked right off Rodizio.

At the end of the day make no mistake that the internet is the mob and the crowd will follow the best image that is reliable, full featured, and easy to use. Rodizio was an upstart and essentially forked and expanded wbc with ez-wbc. The advantage EZ has right now is it’s is probably the easiest to find and most well known and trusted. A new full featured EZ image is a good first new step to keep ppl coming back and hopefully contributions to move things forward. But long term @RespawnDespair is right that the code needs to be structured in a better way for devs and a way for hacks like me to come along and build “my plug-in of the day” and help expand the project. 

This little episode with open-hd is unfortunate and I wished it had been avoided as again it’s a disruptive and a distraction...
