### ISSUE TITLE
Insufficient wiki

### ISSUE THREAD

**Issue by cosmicog** [bortek/EZ-WifiBroadcast#24]
The home page says:

> Insert each SD card into each Raspberry Pi and boot them up.

But they doesn't assign automatically that which one is going to be TX and which one is RX. They're both booting as RX.

How can I set the Transmitter and Receiver Pi?

**Comment by bortek** [comment]
I updated wiki. Check if it is sufficient info now and if yes please close this case yourself. Thanks. 

https://github.com/bortek/EZ-WifiBroadcast/wiki#installation--setup

**Comment by cosmicog** [comment]
Thanks for the responsing quickly.
