### ISSUE TITLE
About FPS Option in Config File

### ISSUE THREAD

**Issue by jiejiecn** [bortek/EZ-WifiBroadcast#26]
Q1: In the config file (line 61)
_Choose between 30, 48, 59.9
FPS = XX_

What if I set FPS = 35 or 45 or 50 ? 

Q2: Why it's 59.9 rather than 60?

**Comment by rodizio1** [comment]
There are three differen hello_video.bin (the program that displays the video) included. 

1. hello_video.bin.48 by mmormota, useable from 48 to 59.9 fps (optimized for smooth playout)
2. hello_video.bin.30 by mmormota, useable for 30fps (optimized for smooth playout)
3. hello_video.bin.240 original by befi, useable for all other fps (but not perfectly smoot playout)

So if you choose either 30fps, or something between 48 and 59.9fps, mmormota's hello_video.bin will be used and you get smoother video, for all other fps settings the "standard" hello_video.bin will be used. 

Not sure exactly why it's 59.9 fps max for mmormota's hello_video.bin, but there is some technical reason.

**Comment by jiejiecn** [comment]
@rodizio1  Thanks. I'll look into that project.
