### ISSUE TITLE
My Tips on Low Latency

### ISSUE THREAD

**Issue by jiejiecn** [bortek/EZ-WifiBroadcast#27]
Recently I achieved a quite good latency, around 100ms under 1280*720 / 48FPS / 4Mbps, using v1.5 with two RPi2

Here're some snapshots with my own program, the number increased by 10 every 10ms. (This is because the response time of LCD display on my laptop and desktop is around 10ms. So with 10ms interval, I can take a clear photo to measure the latency.)
![_20170630215034](https://user-images.githubusercontent.com/11746870/27739243-81343dea-5de0-11e7-894f-930d87f8ce7f.jpg)
![_20170630215029](https://user-images.githubusercontent.com/11746870/27739244-813460c2-5de0-11e7-92a4-335e7689e916.jpg)
![_20170630215026](https://user-images.githubusercontent.com/11746870/27739241-8121a87e-5de0-11e7-8dcd-ddd08fd81942.jpg)
![_20170630215022](https://user-images.githubusercontent.com/11746870/27739242-812975cc-5de0-11e7-93dd-69d3f6f74f8f.jpg)

On Tx side it's RPi2 with WN722N and on Rx side there're two USB AR9271 module for diversity.
![_20170630221401](https://user-images.githubusercontent.com/11746870/27739522-7c017788-5de1-11e7-8f1e-457ed4982d9e.jpg)
![_20170630221404](https://user-images.githubusercontent.com/11746870/27739524-7ed3a652-5de1-11e7-80d9-b942cb9ffbc8.jpg)

The AR9271 is really really a good choice for this purpose. It works under 2.3G~2.4G, I choose 2372MHz which is near 2.4G for antenna and also the channel is clean enough.

Secondly, the USB AR9271 module on Rx side is only $3 and you can find small module with 25dbm RF output for Tx side for only $10

![_20170630222151](https://user-images.githubusercontent.com/11746870/27739838-931c537e-5de2-11e7-94a6-5f263a78d08e.jpg)

Here're some tips:

1. High speed TF card.

This is tricky but it's true! I use SanDisk Ultra 16G Class 10 A1 on both Tx and Rx side. It's much better than Class 4 TF card.

2. GPU / RAM overclock

The video is encoded by GPU on the SoC. So less latency with higher frequency on GPU.
I put GPU and RAM overlock in config.txt
_gpu_freq=500
sdram_freq=500_

3. High FPS

Set the FPS 48 or 60, the higher FPS the less latency. 

4. Camera Sensor Mode

I use RPi Cam v2 and according to the IMX219 specs, set the "-md 6" to force sensor mode to provide high FPS output. 
![picam_imx219_modetable](https://user-images.githubusercontent.com/11746870/27739215-6dba73ec-5de0-11e7-90e7-a53e372039fa.png)

And someone did the test on this.
![picamv2_limit](https://user-images.githubusercontent.com/11746870/27739219-766d69d6-5de0-11e7-80ac-d9d1e5633d86.png)

_EXTRAPARAMS="-n -fl -ih -vf -pf high -md 6 -ISO 400 -ex sports"_

**Comment by pilotnbr1** [comment]
That's pretty good results!

**Comment by bortek** [comment]
Thats a pretty interesting and and good description. I have updated Wiki page (https://github.com/bortek/EZ-WifiBroadcast/wiki/Tips-and-tricks) and reffered to this Issue for those who want to tune their systems for lower latency. I therefore will close this issue for now.

**Comment by az0uz** [comment]
Quick remark on the settings given here, I think most of us wouldn't want to give up half fov for a few ms lower latency, so I wouldn't advise `-md 6` but prefer `-md 4` or `-md 5`
