### ISSUE TITLE
startup order [Question]

### ISSUE THREAD

**Issue by seeul8er** [bortek/EZ-WifiBroadcast#28]
I am currently trying to merge my own project into the wifibroadcast image. I am using the v1.5 images and was wondering how wifibroadcast gets initialized. Meaning:

- where do the wifi interfaces get set up
- where is the code that determines weather it is a RX-Pi or a TX-Pi
- where is the call for `/root/wifibroadcast/tx` etc.

could only find a call for `/root/wifibroadcast_misc/wbcconfig.sh`

Great project! Hope you can give me a little hint  :)

**Comment by az0uz** [comment]
Everything is in /root/.profile

**Comment by seeul8er** [comment]
Damn. That's a little embarrassing :smile: 

Thank you!
