### ISSUE TITLE
Version number in a file

### ISSUE THREAD

**Issue by bortek** [bortek/EZ-WifiBroadcast#29]
Can we have a EZ-WFB version number written in some file on the SD cards FAT partition ( the one visible in WIndows) ? I want to be able to see which image I am working with as I often have different versions testing. 

I suggest a version.txt or in existing wifibroadcast-1.txt , just add a new comment row with "Image version 1.5" or alike.

**Comment by rodizio1** [comment]
Yeah, makes sense, I'll do that.

**Comment by rodizio1** [comment]
will be included in 1.6 RC2
