### ISSUE TITLE
Rx:  Error setting monitor mode on failed!

### ISSUE THREAD

**Issue by tobyfarrar** [bortek/EZ-WifiBroadcast#32]
I just want to start by saying that this is a fantastic project! I always hoped that this was possible, but didn't have the skills to make it happen. So a huge thank you to you for making it happen.

When I first booted up both Pi's everything worked perfectly. I ran the system a couple of times, again perfectly. Today I booted up them both and the Rx Pi came up with the "Error: setting monitor mode on failed!" (I've added a picture of the screen here, not sure why it's upside down, but it come the right way up if you click it)
![20170725_151636](https://user-images.githubusercontent.com/30441786/28585313-d6aad078-7167-11e7-93e2-92098bf5ff2d.jpg)

The only thing I had changed was to enable the wifi hotspot and change the SSID and password. I have re-imaged the SD card with Etcher, but this error keeps happening. Any help would be greatly appreciated.

Thanks

**Comment by rodizio1** [comment]
Looks like either power or wiring problems (then all kinds of strange things can happen ...) or a syntax error or some other problem with wifibroadcast.txt. 

Could it be that you have some GPIOs connected to something? Or that they are broken/malfunctioning? Could be that it's looking for a wifibroadcast-8.txt (or some other configuration profile number, see the Howto section of the wiki).

Can you please post the errorlog.txt from the sdcard here?

**Comment by tobyfarrar** [comment]
[errorlog.txt](https://github.com/bortek/EZ-WifiBroadcast/files/1175825/errorlog.txt)
![errorlog](https://user-images.githubusercontent.com/30441786/28610328-df37d736-71df-11e7-9a86-05539da8b537.png)

It is a Pi 3 Model B and is powered from the official 2.5A 5.1v power supply via the micro USB port. There is nothing attached to the GPIOs. All that is connected is the power, HDMI to the monitor and the CSL-300 adapter into one of the USB ports. The strange thing is that it was working fine the first few times I powered it up. Would you suggest that I power it from a better supply (I have a 5A SBEC that I will be using eventually in the field)?

**Comment by tobyfarrar** [comment]
Update:

I had a spare RPi 3, so I swapped the SD card into it and connected it up and it booted up perfectly. I put the card back in the original one and it has the same error. I guess therefore it is a problem with the board?

**Comment by rodizio1** [comment]
Yes, this looks like one or more GPIOs is broken which causes a different wifibroadcast.txt to be selected (which doesn't exist). See here for an explanation of that feature: https://github.com/bortek/EZ-WifiBroadcast/wiki/How-to's#using-configuration-profiles

A quick workaround would be to copy over the wifibroadcast-1.txt to wifibrocast-2.txt and so on up to wifibroadcast-8.txt.

Better way would be completely removing that feature, I can look up how to do that later.

**Comment by tobyfarrar** [comment]
I did your workaround and that has sorted it out. Thank you so much for your help. I will test the GPIOs on this board and see what that problem is, but at least for now it is fully functional.
