### ISSUE TITLE
Data rates, frames and drivers

### ISSUE THREAD

**Issue by seeul8er** [bortek/EZ-WifiBroadcast#34]
I am a little confused and hope someone can help me out.
I seems like that:

- **Data frames** are used with a **Ralink** wifi chips
- **Beacon frames** are used with **Atheros** chips

In both cases the packets get sent correctly in wifibroadcast using the specified data rate.

**Question: Can I send standard data frames with a Atheros chipset and specify the data rate?**

Background:
I tried to send data frames with a Atheros chipset using a custom kernel (patched with wbc patches). In the radiotap header I set the data rate. Testing it I found the data rate of the sent frame was always 1Mbit regardless of my changes in the radiotap header.
Everything works fine using Ralink based wifi equipment.

In the code I found:
`-d <rate>   Data rate to send frames with. Currently only supported with Ralink cards. Choose 6,12,18,24,36 Mbit`
If that is still the case in wbc 1.5 how does it set the correct bit rate with Atheros chips? Via `iw ...` or is the Atheros driver only patched to work with beacon frames?
Thought it would be nice to have one type of frame that workes with both chips.

**Comment by rodizio1** [comment]
What type of frame is used depends on chipset and if CTS protection is enabled. Ralink always uses data (as beacons don't work with ralink). Atheros uses beacons with CTS off, and data with CTS on. The Atheros firmware is patched to send CTS frames when data frames get injected. For beacons, the firmware doesn't do this.

Bitrates are set during card initialization at bootup for both Atheros and Ralink. Ralink cards support setting of bitrates via radiotap header (for kernel 4.4 a patch is required, 4.9 can do it without patch), Atheros don't. 


Quite awkward construction, but works fine :)

Much nice would be though if I could set bitrates (802.11b, 802.11g, 802.11n) and CTS solely through the radiotap headers, but I don't have the kernel knowledge and C skills to do it.

It's possible though, these guys have done it:
https://moep80211.net/plink/lcn2016/
