### ISSUE TITLE
Question about diversity WIFI compose on receiver side

### ISSUE THREAD

**Issue by AAV514** [bortek/EZ-WifiBroadcast#37]
Hi, 
I have some question.

1.  I read this,  
     3 wifi sticks receive diversity support for Atheros
     5 wifi sticks receive diversity support for Ralink

     then, how about MediaTek MT7601? 
     Is it 5, same to Ralink?

2.   I want to make a 2~5 WIFI diversity receiver. 
 
      but  I don't want to use  USB port type WIFI stick at all, because it is too bulky.

      Can I compose a 2~5 WIFI diversity receiver without use of USB port connection?

      I mean, can I connect 2~5 WIFI cards with  RPi 3 by use only the GPIO pin?

3.  I plan to use Pi ZERO as a transmitter, because of it's small size. 

     TX: The CPUs on the Raspberry Pi 1 and Pi Zero are more or less maxxed out with standard settings
     (6Mbit bitrate, 8/4/1024 FEC). Two TX dongles, higher resolution/bitrate, or more error correction or
     smaller packet sizes will most likely not work.
   
     had better not to use diversity function on Pi ZERO transmitter?

4.   if  TXMODE option set as 'single' on Pi ZERO transmitter side,   
       I also can't  activate  diversity receiver function on Pi 3 transmitter?
       
      I'm wondering is  can I make this kinds of system. 
      - One WIFI card attached on Pi ZERO transmitter side, single mode setting.
      - Multiple WIFI cards attached on Pi 3 receiver side, multi mode setting. 
      - All WIFI cards attached on Pi 3 receiver side use same frequency, 
        act like a analog diversity fpv system antenna . 

      Is this possible?

**Comment by rodizio1** [comment]
1. Yes, MT7601 uses the Ralink driver, so 5 cards should work.

2. Not possible. But you can de-solder all the USB plugs and sockets on the USB dongles and the Pi (for the TX, this is mandatory anyway ...) and solder wires directly, this makes it a lot smaller. 

3. Two TX dongles on the Pi0 or Pi1 is not possible, not enough CPU power to do that.

4. You can use either one dongle on the TX (one frequency), or use the dual-TX function with two dongles on the TX (on two different frequencies). Two TX dongles on the same frequency won't work.

The dual-TX function with two dongles works only with Ralink (and the MT7601) dongles both on TX and RX, Atheros gives timing issues and thus badblocks.

One TX dongle combined with multiple RX dongles is the default, there is nothing that needs to be setup for that, it just works.

**Comment by AAV514** [comment]
Really thanks a lot~!!
every question has been resolved
