### ISSUE TITLE
What should I do for the next step?

### ISSUE THREAD

**Issue by AAV514** [bortek/EZ-WifiBroadcast#47]
Hi, 
I connected two 8811au wifi cards on rpi 3 RX.
wifi cards installed as a monitor mode.
What should I do for the next step?
just make the TX, is it enough?
or 
need  some setting?

![20170924_033433](https://user-images.githubusercontent.com/20312319/30776106-94b9713a-a0db-11e7-8a5f-a70f25210de4.jpg)

and How to connect a RPI to pixhawk? I want to make OSD system

**Comment by rodizio1** [comment]
Sorry I can't help you there, Realtek is unsupported and I don't have Realtek hardware to test with.

What I can see from the picture though is, that your wiring and/or power supply is not adequate, it says "throttled=0x50005" (means the Pi firmware detected power problems). See the Wiki for wiring instructions.

**Comment by AAV514** [comment]
Yes.  might be power problems. 
I used a  5V 1A, USB charger for test.
