### ISSUE TITLE
5mhz and 10mhz channels

### ISSUE THREAD

**Issue by geofrancis** [bortek/EZ-WifiBroadcast#48]
on my ubiquiti routers you could select 5 and 10 mhz channels rather than just the usual 20 and 40mhz channels, this would give many more separate channels in the crowded 2.4ghz band but i have never seen it on any other wifi hardware so im not even sure it would be possible.

**Comment by rodizio1** [comment]
The linux drivers don't support the narrower channel widths for USB chipsets, there's nothing I can do.

**Comment by geofrancis** [comment]
i think there is now support in the driver for 5/10mhz modes 

http://www.qsl.net/kb9mwr/projects/wireless/modify.html

**Comment by rodizio1** [comment]
Sorry, this doesn't apply to AR9271 usb dongles. Not possible.

**Comment by geofrancis** [comment]
ah well.
