### ISSUE TITLE
make hotspot name and password customisable

### ISSUE THREAD

**Issue by geofrancis** [bortek/EZ-WifiBroadcast#50]
i am looking to run a munber of machines at the same time but i would like to change the name of the hotspot to match the machine. so im not blindly trying multiple hotspots that all have the same name and password

**Comment by seeul8er** [comment]
#Take a look at the `apconfig.txt` which is in the same location as the `wifibroadcast-1.txt`

At the very top of the file you can change the access point settings:

`channel=1`
`ssid=NewAccessPointName`
`wpa_passphrase=password`

**Comment by geofrancis** [comment]
i have been playing with 1.3beta for a long time i didnt realise that had been added in the newer versions
