### ISSUE TITLE
how to adjust cmavnode.conf ?

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#53]
Hello, I have an issue with sysid 01 send from my ground control sofware, that crash cmavnode.

I attempt to change cmavnode.conf file  by adding this parameter:
output_only_from=1

but it does not affect anything.

What I make wrong?

could you help me and tell me how to adjust cmavnode.conf for the change take effects?

**Comment by rodizio1** [comment]
Sorry for the late reply. Did you get it working? The file is located in /root/cmavnode/.

If you search for "cmavnode.conf" in the /root/.profile script, you can see what's happening, it's being taken from /root/cmavnode/, copied over to /tmp/ and then the IP is added to it.

So if you add an option to /root/cmavnode/cmavnode.conf, that option should be used.
