### ISSUE TITLE
record osd with the video 

### ISSUE THREAD

**Issue by geofrancis** [bortek/EZ-WifiBroadcast#55]
having an option for recording the osd along with the video feed would be very useful for diagnostics and for recovering aircraft.

**Comment by rodizio1** [comment]
Unfortunately not possible, that would mean decoding, inserting the OSD and re-encoding the videostream on the Pi.

For recovering aircraft, telemetrylog.txt is saved on a usb stick, it contains all telemetry data like latitude/longitude, height, speed etc.

More fancy would be converting the data into a Google Earth .kml file and saving that to USB, but that's still on my todo list.

**Comment by matiaspl** [comment]
Not that impossible. There's https://github.com/DougGore/telepi. RPi is
capable of decoding and encoding (and scaling) at the same time.

14.11.2017 16:11 "geofrancis" <notifications@github.com> napisał(a):
