### ISSUE TITLE
More dip switch combinations

### ISSUE THREAD

**Issue by glatorg** [bortek/EZ-WifiBroadcast#60]
I would like to choose more than 8 different frequencies/configurations on the RX

**Comment by rodizio1** [comment]
I'll look into that, another pin for 16 combinations should be no problem.

**Comment by glatorg** [comment]
Super! 16 combinations it's ok but 32 should be better because you can cover almost every frequency available for Atheros.

**Comment by geofrancis** [comment]
16 is overkill, most channels overlap so you don't need that many

**Comment by rodizio1** [comment]
V1.6RC3 now supports 16 combinations. Additional GPIO pin used is BCM1 (or pin 28, see http://pinout.xyz). If you need additional combinations, simply use additonal SD cards as a workaround for now. In the long run, configuration will hopefully be made easier.

**Comment by mathiasseyfert** [comment]
Is it correct that these pins are ment to be connected to the 3.3V GIPO in order to trigger a profile change? thank you
