### ISSUE TITLE
1.6RC2 ALFA AWUS052NH v2 only support 11mbit

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#61]

**Comment by rodizio1** [comment]
Did you check on the TX or RX? The RX always shows lower bitrates (as the bitrate you see there is for the r/c and telemetry uplink).

I've tested different bitrates, they all work so far. If you leave default settings (18mbit wifi datarate), you should get around 6-6.5mbit videobitrate on auto settings.

Do you have good wiring and powersupply? The card draws up to 1.8amps under 'full load' which is the case when 1.6 does the bitrate measuring before starting the transmission.

**Comment by roque-canales** [comment]
Thank you for this support, issue is resolved instaling low esr caps on wifiboards

**Comment by rodizio1** [comment]
great, thanks for reporting back.
