### ISSUE TITLE
Disabling the OSD and Telemetry in v1.6RC2

### ISSUE THREAD

**Issue by EmbeddedMe** [bortek/EZ-WifiBroadcast#63]
What is the best way to completely disable the OSD and telemetry functions in v1.6RC2?

**Comment by rodizio1** [comment]
If you disable all the features in the osdconfig, there should be nothing visible left, although the osd is technically still running then, just not displaying anything. Disabling it completely could be done by putting some syntax error in the osdconfig which would prevent the osd from being started at all. But I've never tested if that may cause other issues, best would be to look through the .profile script and search for 'osd'.

**Comment by EmbeddedMe** [comment]
Thank you very much for the tips - I appreciate it. I will look look into your suggestions and see what works best. I just wanted to make sure that I was not missing a more direct method of disabling it.
