### ISSUE TITLE
Edit wifibroadcast-1.txt trough SSH

### ISSUE THREAD

**Issue by glatorg** [bortek/EZ-WifiBroadcast#66]
with ETHERNET_HOTSPOT=N
connecting RX to the router via cable, on display appears " Ethernet connected. IP 192.168..."
Via SSH with "root" user and default password I can see the Boot folder but I can't edit "wifibroadcast-1.txt" filezilla says: 
`Error:  /boot/wifibroadcast-1.txt: open for write: received failure with description 'Failure'`
Some idea?

**Comment by matiaspl** [comment]
All mounts are write-protected by default. Enter "rw", press enter and
you're good to go.

2017-12-13 15:30 GMT+01:00 glatorg <notifications@github.com>:

**Comment by glatorg** [comment]
Thank you!
