### ISSUE TITLE
Streaming from UVC source (EASYCAP dongle connected to mobius /runcam camera)

### ISSUE THREAD

**Issue by bazyl78** [bortek/EZ-WifiBroadcast#68]
How to change this part of TX to use uvc stream from EASYCAP usb dongle (mJPEG format, SD, needs to be transcoded to h264):

#    nice -n -9 cat /dev/video0 | /root/wifibroadcast/tx_rawsock -p 0 -b $VIDEO_BLOCKS -r $VIDEO_FECS -f $VIDEO_BLOCKLENGTH -t $VIDEO_FRAMETYPE -d $VIDEO_WIFI_BITRATE -y 0 $NICS

Probably I need to use gst-launch but don't know how to pipeline it to /root/wifibroadcast/tx_rawsock

**Comment by rodizio1** [comment]
Sorry, can't help much there have not much knowledge about gstreamer and usb and other cams, the above commandline works with the raspberry cam and doesn't do any transcoding.

I'd first try making a gst-launch commandline work that puts out a transcoded h264 stream and pipes the stream directly to hello_video.bin (or another videplayer). When that works, put the wbc tx_rawsock and rx in-between. When transcoding the stream, you will probably have to make use of the raspberry GPU for transcoding as the CPU will probably be too slow.
