### ISSUE TITLE
Add bidirectionnal telemetry link as for the joystick up link

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#7]
Hello,

Does anyone can help me to be able to send telemetry from rx to tx?

I think that as for the joystick, we can send from RX serial data to TX.

Also, it could be great, to be able to have en the rx side TCP or UDP serial server.

Like this no need cables between RX and LAPTOP.

**Comment by bortek** [comment]
As discussed via email please formulate your question clearly and it on projects forums page (See Wiki for link). Hopefully someone can help you out.
