### ISSUE TITLE
RPI3 wifi chipset support

### ISSUE THREAD

**Issue by lvale** [bortek/EZ-WifiBroadcast#70]
Is there a way to just use the onboard wifi chipset of the RPI3 ? I see that it has support to monitor mode, so I'm not sure what would be required https://github.com/seemoo-lab/nexmon

edit: I see that @rodizio1 already has knowledge of the project above https://github.com/seemoo-lab/nexmon/issues/101

**Comment by rodizio1** [comment]
As you have already seen, injection speed is the problem. It could still be used on the receive side though, but it's limited to channels 1-13 and there is the Wifihotspot functionality which already uses the onboard chip, so I haven't put any effort into making it useable in monitor mode.

**Comment by lvale** [comment]
I think that having the option, even with the issue of injection speed, would make it easy to start easily.
