### ISSUE TITLE
Quick Question: autostarting wifibroadcast

### ISSUE THREAD

**Issue by tictag** [bortek/EZ-WifiBroadcast#75]
@rodizio1 I just spent the entire of yesterday trying to find out how wifibroadcast auto-started. I went through: rc.local, .bashrc, init.d directory, systemd & cron auto-start systems (_Google was my friend_) and could only find where the "WifiBroadcast v1.4RC4 ....." text is displayed via /init.d/raspi-config. I can clearly see from the bootup sequence behaviour that the "profile" bash script in /wifibroadcast-scripts is how wifibroadcast is executed but just can't find where this script is called from.

QQ: Where is the "profile" bash script called from?

**Comment by matiaspl** [comment]
Mind the dot. It's in /root/.profile

15.01.2018 12:29 "tictag" <notifications@github.com> napisał(a):

**Comment by tictag** [comment]
Wow, what a learning curve. So I've now learned that wifibroadcast auto-logs into the console on boot using `systemctrl set-default multi-user-target`, that something called a 'symbolic link' exists between `/etc/systemd/system/autologin@.service`  and `/etc/systemd/system/getty.target.wants/getty@tty1.service`, which is configured to login as `root` and that the `.profile` file is autorun on login to the console, so by executing `tx_rawsock` within `.profile` in `root`'s home directory wifibroadcast automatically runs.

oh, and grep doesn't search through hidden files unless you explicitly tell it to.....grrrr.

Linux sucks.

**Comment by rodizio1** [comment]
Yes, there is autologon configured in systemd for tty1-tty12. After logon, the shell (bash in this case), is started which then starts the .profile script. The .profile scripts then looks on what tty it is running to decide what functionality (video rx, osd, telemetry, joystick r/c, etc.) is to be run on that tty.

Yeah, Linux is a mess.

**Comment by tictag** [comment]
LOL! Hilarious! Never seen Linux 'blue screen' before ;)
