### ISSUE TITLE
Sending multiple video streams through wifibroadcast

### ISSUE THREAD

**Issue by tictag** [bortek/EZ-WifiBroadcast#76]
Two queries regarding transmitting multiple video streams:

1  Would I be correct to assume that I can tx/rx multiple video streams by executing tx_rawsock twice configured with two different ports using the `-p` argument? For example:

- cat /dev/**stream1** | tx_rawsock **-p 5600** -b 8 -r 4 -f 1024 -t 1 -d 24 -y 0 wlan0
- cat /dev/**stream2** | tx_rawsock **-p 5700** -b 8 -r 4 -f 1024 -t 1 -d 24 -y 0 wlan0

2  If so, what would be the performance impact of doing so e.g. halved data-rate = no impact?

**Comment by rodizio1** [comment]
I have never tried it with two videostreams, but yes, that should be possible. Datarate should be halved. Portnumbers are limited from 0-127 though.

You can test datarate with the "pv" tool, `cat /dev/stream1 | pv -i 0.5 -r | tx_rawsock ...` will show the datarate flowing through the pipe.

Or to test max. theoretical throughput you can do something like `cat /dev/zero  | pv -i 0.5 -r | tx_rawsock ...`
