### ISSUE TITLE
Move parameters in wifibroadcast-1.txt

### ISSUE THREAD

**Issue by glatorg** [bortek/EZ-WifiBroadcast#78]
Some parameters now in the section 
**# Common settings (need to be kept in sync for both TX and RX!)**
Should not be there, for example:
SHOW_BITRATE
DATARATE
VIDEO_BITRATE
BITRATE_PERCENT
seems to me that they acts only when changed on the TX side.

**Comment by rodizio1** [comment]
Hmm, you're right, not sure why they ended up under common settings. I'll move them to the TX section in the next release.

**Comment by rodizio1** [comment]
Fixed in 1.6RC4.
