### ISSUE TITLE
linux-4.9.28-dwc-otg.patch issues

### ISSUE THREAD

**Issue by tictag** [bortek/EZ-WifiBroadcast#79]
All other patch files work perfectly, except `linux-4.9.28-dwc-otg.patch`. When this patch is executed the console reports errors similar to, "Hunk 1 OK, Hunk 2 failed....." (didn't capture the exact error). When subsequently compiling the kernel, the compile fails when these files are reached.

When comparing this patch file to v4.9.35 of the RPi kernel source code, most of the changes appear already to be implemented and the one section that isn't doesn't intuitively look correct - please see attached screenshots for detailed analysis.

As a workaround for the patch failing, I manually updated the affected source files (`dwc_otg_driver.c` & `dwc_otg_hcd_queue.c`), after which the kernel compiled OK.

For others, would you be able to review the attached and update the patch file accordingly?

![2018-01-22_03-14-15](https://user-images.githubusercontent.com/12136834/35204544-c87175be-ff26-11e7-9bd2-a7cbdebbb758.png)
![2018-01-22_03-15-45](https://user-images.githubusercontent.com/12136834/35204543-c853fc8c-ff26-11e7-9fe9-57ad0212fd79.png)
![2018-01-22_03-16-52](https://user-images.githubusercontent.com/12136834/35204542-c8346d0e-ff26-11e7-92f8-8d70d109d016.png)
![2018-01-22_03-18-18](https://user-images.githubusercontent.com/12136834/35204541-c815730e-ff26-11e7-92b7-205339ea4ad5.png)
![2018-01-22_03-19-12](https://user-images.githubusercontent.com/12136834/35204540-c7f91ad8-ff26-11e7-842b-24b1268c9805.png)

**Comment by rodizio1** [comment]
I made these patches for 4.9.28 initially. It's this feature (which turned out to not work later anyway ...): https://github.com/raspberrypi/linux/pull/2067. Shortly after, a new Raspbian release with 4.9.35 came out which had that particular patch already integrated, so with 4.9.35, the patch isn't needed.

I'm not sure what your manual changes do, I'd rather revert them.

**Comment by tictag** [comment]
Ahh, got you. Might be worthwhile modifying the readme.md in /kernel to mention this, save other newbies from making the same mistake, especially as it took quite some time to get the place where it failed! ;) Suggest the following change:

FROM: `Patches also apply to kernel 4.9.35 included in Raspbian 2017-07-05`
TO: `All patches except linux-4.9.28-dwc-otg.patch also also apply to kernel 4.9.35 included in Raspbian 2017-07-05`

**Comment by rodizio1** [comment]
Well, it's quite clear when looking at the sources. Regarding the image with the text "Patch deletes then reinserts the same code": No it doesn't, there are some "//" added.

I've changed the text in the readme.
