### ISSUE TITLE
SHOW_BITRATE not recognized

### ISSUE THREAD

**Issue by neilyoung** [bortek/EZ-WifiBroadcast#80]
Even though I have set SHOW_BITRATE=N in wifibroadcast-1.txt I'm seeing the display of the bitrate in the top right line of the rx screen.

I cannot even see, that this setting is used anywhere in the code

How to get rid of this?

**Comment by seeul8er** [comment]
Works fine with me.
You must change the setting on the drones pi image. Will not have any effect if you just change on groundstation side.

**Comment by neilyoung** [comment]
Hi @seeul8er, thanks. Stupid me, I changed it on the RX side only... Yes, indeed, now it is gone.
