### ISSUE TITLE
Under-voltage or over temperature on TX!

### ISSUE THREAD

**Issue by neilyoung** [bortek/EZ-WifiBroadcast#83]
Getting this warning on RX screen. I can see, where it is generated, but I don't know the reason. Temperature and voltage seem to be fine...

Can I get rid of this somehow?

**Comment by rodizio1** [comment]
If you have just started the Pi and get the message it can't be too high temperature (that would take longer to heat up), then it's bad power supply and/or wiring.

**Comment by neilyoung** [comment]
@rodizio1 Hmm. I don't think it is temperature related. And the hw design is not mine. But it seems to be pretty robust (it is the Sunfounder robot car https://www.sunfounder.com/robotic-drone/smartcar/smart-video-car-kit.html), but of course it might have issues. 

Is there a way to remove or to suppress it?

**Comment by geofrancis** [comment]
have you checked the voltage that the pi is getting is actually 5v?

**Comment by neilyoung** [comment]
4.82

**Comment by geofrancis** [comment]
thats low. you should get another regulator.

**Comment by neilyoung** [comment]
It is this https://www.amazon.de/SunFounder-DC-DC-Converter-Module-Raspberry/dp/B014KSY13O, fed with 12 V input.

**Comment by geofrancis** [comment]
you should use a separate bec for the pi.

**Comment by neilyoung** [comment]
@geofrancis No the same happens to a brand new RPI3 powered with the original power plug or a power pack 5V 2A. Maybe the expectations need to be lowered.

**Comment by rodizio1** [comment]
The stepdown regulator on your car is rated 2A. The instructions in the wiki state you need a 3A power supply. The wires are surely not atleast 0.5qmm like it is recommended in the instructions. USB power banks suck in general, the instructions say not to use them. You are measuring 4.82V, the instructions say you need 5V ...

Just follow the wiring instructions and it'll work fine.
