### ISSUE TITLE
1.6RC3 no flightmode in OSD

### ISSUE THREAD

**Issue by FritzWalter123** [bortek/EZ-WifiBroadcast#88]
Hello,
so far, all informations from mavlink will be displayed on screen except flightmode. 
Not implemented until now or a bug?

**Comment by rodizio1** [comment]
Not implemented (yet). 

There are two users who made extensions to the OSD for version 1.5 and also posted the code, but I haven't found time yet to integrate it.

If you want to try it yourself:
https://www.rcgroups.com/forums/showpost.php?p=38130691&postcount=3163
https://www.rcgroups.com/forums/showpost.php?p=38138774&postcount=3172

**Comment by FritzWalter123** [comment]
Thanks a lot for the great job here!  

I try it out on my 1.6RC3 image. but get a segmentation fault when starting the osd binary. I think something has changed to 1.5.  I will spend some more time to this the next days.

**Comment by FritzWalter123** [comment]
Hi...i merged the osd stuff in src from 1.6rc3.  There were some merge conflicts to 1.5. Seems to work now. Do you want to have the src ? What is the best way to forward it?  Regards

**Comment by rodizio1** [comment]
Now that was fast. Did you merge both? Would be great if you can attach it here (or on the rcgroups thread) or upload it somewhere.

**Comment by FritzWalter123** [comment]
[osd_patch_for _16RC3.tar.gz](https://github.com/bortek/EZ-WifiBroadcast/files/1688386/osd_patch_for._16RC3.tar.gz)

**Comment by FritzWalter123** [comment]
[osd_patch_for _16RC3.tar.gz](https://github.com/bortek/EZ-WifiBroadcast/files/1688487/osd_patch_for._16RC3.tar.gz)
A crosscheck would be a good idea. Only connected on ground with my apm and not flown yet.

**Comment by rodizio1** [comment]
Thanks for helping, really appreciate it. I'll look into it on the weekend.

**Comment by rodizio1** [comment]
features are integrated in 1.6RC5 now.
