### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by mic159** [bortek/EZ-WifiBroadcast#9]
I see that you are putting ZIP files from google drive and linking to them on the wiki.

It might be better to tie the downloads to a git version by using "releases"/tags here on GitHub instead, and attaching the ZIPs to the release.
You can also put release notes on each version.

For example: https://github.com/phw/peek/releases

**Comment by bortek** [comment]
mic thanks for your suggestion. We will consider it for future releases.
