### ISSUE TITLE
connect to usb serial devices ground pi via hotspot.

### ISSUE THREAD

**Issue by geofrancis** [bortek/EZ-WifiBroadcast#90]
I have a RTK gps and a serial servo controller antenna tracket that I connect to over usb using mission planner, if you could forward usb serial devices to a udp port then I could run it all over the hotspot.

**Comment by rodizio1** [comment]
sorry I don't have any devices to test that with and too many other things on my list.

**Comment by geofrancis** [comment]
I have done this before when i used to hack routers, I think it was ser2net i used to forward a serial port so i could monitor the battery management controller over wifi , it just forwards a serial port to a network port, but that was about 10 years ago when i was running openWRT I am not sure how i would add it to wifibroadcast or if it would interact with wifibroadcasts usage of serial ports.
