### ISSUE TITLE
Add video switch for chose in flight between raspi cam and usb webcam

### ISSUE THREAD

**Issue by roque-canales** [bortek/EZ-WifiBroadcast#91]

**Comment by careyer** [comment]
+1 vote for such a feature. It would be great to have a feature to switch between two different video sources in mid-flight. I want to use something similar to switch between HD-Video and Thermal-Video. 

@rodizio1 : You might be able to adapt some parts of Franks (dinos) OSD for that. He implemented a function to switch between different OSD screens on the GroundPi via the USB/Taranis. As far as he explained to me he writes all the channels from the Taranis to a memory structure in the GroundPi and from there all channels can be read and used for various things, e.g. to switch OSD screens 1...3 by a 3 position switch.

That would be AWESOME!

**Comment by rodizio1** [comment]
sorry, this is way too much work at the moment and also probably wouldn't work as there are different usb cameras I cannot test with.
