### ISSUE TITLE
[1.6 RC3] ERROR: wifobroadcast config file not found!

### ISSUE THREAD

**Issue by MattMgn** [bortek/EZ-WifiBroadcast#92]
Hello,

I get this message at the first line when I plug a screen to my PI3. Someone know why ?
_wifibroadcast-1.txt_ is well located at sd card's root

Matt

**Comment by careyer** [comment]
Did you connect something to the GPIO that causes WiFiBroadcast to search for a wifibroadcast-2.txt file maybe? 

Von meinem iPhone gesendet

**Comment by MattMgn** [comment]
Exactly ! I have just removed sensor HAT, and it's working

Thks
