### ISSUE TITLE
Splash Screen Overwrite

### ISSUE THREAD

**Issue by csteamengine** [bortek/EZ-WifiBroadcast#96]
Hello again, 
I have been thinking of making my own custom splash screen, and I know there is a line in the config file to disable the splash, but I was wondering where the actual splash file is located so I could just override it. If anyone knows where that file is located, that would be awesome. If not, then I can always just disable it and then implement my own splash screen, and see if that works.

Thanks!

**Comment by csteamengine** [comment]
Just checking back to see if anyone knows how to overwrite the splash screen that just says "EZ-WifiBroadcast 1.6 (RC3)" or something like that. Thanks in advance!

**Comment by seeul8er** [comment]
Take a look at `/etc/init.d/` on your wbc-image. Somewhere in there must be a start-script that calls `wifibroadcast_status/wbc_status [some parameters]`

wbc_status is the programm that displays the text.

I do not have the image at hand but I hope this is pushes you in the right direction

**Comment by tictag** [comment]
I don't think the "EZ-WifiBroadcast 1.6 (RC3)" is actually a splash screen (image), more that the code first loads a graphics code snippet then displays it as large font text. I can't remember where it is but if you clone the repository then search for the splash screen text, you'll find where it is called. For a simple update, just change the text and recompile. For a more advanced update, you'll need to know how to manipulate the graphics code (I'm guessing it's open source so docs will be available somewhere).

**Comment by rodizio1** [comment]
Yes, it's the same tool that also display the status messages like "2nd display detected" etc.
It's called in /etc/init.d/raspi-config (which gets started early during boot-up, that's why it's in that script).

**Comment by csteamengine** [comment]
Ok, I was able to finally locate that line of text, thank you guys for your help!
